import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

@Injectable()
export class AttendancePerformanceService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  listAttendance(employeeId?: string, from?: string, to?: string) { return this.prisma.attendanceRecord.findMany({ where: { deletedAt: null, ...(employeeId ? { employeeId } : {}), ...(from || to ? { attendanceDate: { ...(from ? { gte: this.date(from) } : {}), ...(to ? { lte: this.date(to) } : {}) } } : {}) }, include: { employee: true }, orderBy: [{ attendanceDate: "desc" }, { createdAt: "desc" }] }); }
  async createAttendance(input: { employee_id: string; attendance_date: string; attendance_type: string; work_hours?: string; overtime_hours?: string; attachment?: unknown[]; remark?: string }, user: CurrentUser) { await this.employee(input.employee_id); const row = await this.prisma.attendanceRecord.create({ data: { employeeId: input.employee_id, attendanceDate: this.date(input.attendance_date), attendanceType: input.attendance_type, workHours: input.work_hours ? this.nonNegative(input.work_hours, "INVALID_WORK_HOURS") : undefined, overtimeHours: input.overtime_hours ? this.nonNegative(input.overtime_hours, "INVALID_OVERTIME_HOURS") : undefined, attachment: (input.attachment ?? []) as Prisma.InputJsonValue, remark: input.remark, ...this.audit.create(user) } }); await this.audit.record("attendance.create", "attendance_record", user.id, row.id, { employee_id: row.employeeId, attendance_date: input.attendance_date }); return row; }
  async updateAttendance(id: string, input: { attendance_date?: string; attendance_type?: string; work_hours?: string; overtime_hours?: string; attachment?: unknown[]; remark?: string }, user: CurrentUser) { await this.getAttendance(id); const row = await this.prisma.attendanceRecord.update({ where: { id }, data: { ...(input.attendance_date === undefined ? {} : { attendanceDate: this.date(input.attendance_date) }), ...(input.attendance_type === undefined ? {} : { attendanceType: input.attendance_type }), ...(input.work_hours === undefined ? {} : { workHours: this.nonNegative(input.work_hours, "INVALID_WORK_HOURS") }), ...(input.overtime_hours === undefined ? {} : { overtimeHours: this.nonNegative(input.overtime_hours, "INVALID_OVERTIME_HOURS") }), ...(input.attachment === undefined ? {} : { attachment: input.attachment as Prisma.InputJsonValue }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }); await this.audit.record("attendance.update", "attendance_record", user.id, id); return row; }
  async removeAttendance(id: string, reason: string, user: CurrentUser) { if (!reason?.trim()) throw this.invalid("DELETION_REASON_REQUIRED", "删除考勤必须填写原因"); await this.getAttendance(id); const row = await this.prisma.attendanceRecord.update({ where: { id }, data: { deletedAt: new Date(), deletedBy: user.id, updatedBy: user.id, remark: reason } }); await this.audit.record("attendance.delete", "attendance_record", user.id, id, { reason }); return row; }
  listPerformance(employeeId?: string, periodStart?: string, periodEnd?: string) { return this.prisma.performanceRecord.findMany({ where: { deletedAt: null, ...(employeeId ? { employeeId } : {}), ...(periodStart ? { periodStart: this.date(periodStart) } : {}), ...(periodEnd ? { periodEnd: this.date(periodEnd) } : {}) }, include: { employee: true }, orderBy: { periodStart: "desc" } }); }
  async createPerformance(input: { employee_id: string; period_start: string; period_end: string; score?: string; grade?: string; reward_amount?: string; comment?: string; attachment?: unknown[] }, user: CurrentUser) { await this.employee(input.employee_id); const start = this.date(input.period_start); const end = this.date(input.period_end); if (end < start) throw this.invalid("INVALID_PERFORMANCE_PERIOD", "绩效期间无效"); const row = await this.prisma.performanceRecord.create({ data: { employeeId: input.employee_id, periodStart: start, periodEnd: end, score: input.score ? new Prisma.Decimal(input.score) : undefined, grade: input.grade, rewardAmount: input.reward_amount ? new Prisma.Decimal(input.reward_amount) : undefined, comment: input.comment, attachment: (input.attachment ?? []) as Prisma.InputJsonValue, ...this.audit.create(user) } }); await this.audit.record("performance.create", "performance_record", user.id, row.id); return row; }
  async updatePerformance(id: string, input: { score?: string; grade?: string; reward_amount?: string; comment?: string; attachment?: unknown[] }, user: CurrentUser) { await this.getPerformance(id); const row = await this.prisma.performanceRecord.update({ where: { id }, data: { ...(input.score === undefined ? {} : { score: new Prisma.Decimal(input.score) }), ...(input.grade === undefined ? {} : { grade: input.grade }), ...(input.reward_amount === undefined ? {} : { rewardAmount: new Prisma.Decimal(input.reward_amount) }), ...(input.comment === undefined ? {} : { comment: input.comment }), ...(input.attachment === undefined ? {} : { attachment: input.attachment as Prisma.InputJsonValue }), ...this.audit.update(user) } }); await this.audit.record("performance.update", "performance_record", user.id, id); return row; }
  async removePerformance(id: string, reason: string, user: CurrentUser) { if (!reason?.trim()) throw this.invalid("DELETION_REASON_REQUIRED", "删除绩效必须填写原因"); await this.getPerformance(id); const row = await this.prisma.performanceRecord.update({ where: { id }, data: { deletedAt: new Date(), deletedBy: user.id, updatedBy: user.id, comment: reason } }); await this.audit.record("performance.delete", "performance_record", user.id, id, { reason }); return row; }
  private async employee(id: string) { const row = await this.prisma.employee.findFirst({ where: { id, deletedAt: null } }); if (!row) throw this.notFound("EMPLOYEE_NOT_FOUND", "员工不存在"); return row; }
  private async getAttendance(id: string) { const row = await this.prisma.attendanceRecord.findFirst({ where: { id, deletedAt: null } }); if (!row) throw this.notFound("ATTENDANCE_NOT_FOUND", "考勤记录不存在"); return row; }
  private async getPerformance(id: string) { const row = await this.prisma.performanceRecord.findFirst({ where: { id, deletedAt: null } }); if (!row) throw this.notFound("PERFORMANCE_NOT_FOUND", "绩效记录不存在"); return row; }
  private date(value: string) { const date = new Date(`${value}T00:00:00.000Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(date.valueOf())) throw this.invalid("INVALID_DATE", "日期无效"); return date; }
  private nonNegative(value: string, code: string) { try { const result = new Prisma.Decimal(value); if (result.lt(0)) throw new Error(); return result; } catch { throw this.invalid(code, "数值不能为负数"); } }
  private notFound(code: string, message: string) { return new NotFoundException({ code, message, details: [] }); }
  private invalid(code: string, message: string) { return new UnprocessableEntityException({ code, message, details: [] }); }
}
