import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

@Injectable()
export class PayrollLedgerService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async list(employeeId?: string, periodStart?: string, periodEnd?: string, status?: string) { return this.prisma.payrollLedger.findMany({ where: { deletedAt: null, ...(employeeId ? { employeeId } : {}), ...(periodStart ? { periodStart: this.date(periodStart) } : {}), ...(periodEnd ? { periodEnd: this.date(periodEnd) } : {}), ...(status ? { status } : {}) }, include: { employee: true, adjustments: { where: { deletedAt: null } }, allocations: { where: { deletedAt: null } } }, orderBy: { periodStart: "desc" } }); }
  async get(id: string) { const row = await this.prisma.payrollLedger.findFirst({ where: { id, deletedAt: null }, include: { employee: true, adjustments: { where: { deletedAt: null } }, allocations: { where: { deletedAt: null } } } }); if (!row) throw this.notFound("PAYROLL_LEDGER_NOT_FOUND", "薪资台账不存在"); return row; }
  async generate(input: { employee_id: string; period_start: string; period_end: string; currency: string; base_salary?: string; overtime_amount?: string; attendance_deduction?: string; performance_amount?: string; allowance_amount?: string; social_insurance?: string; individual_tax?: string; other_adjustment?: string; attachment?: unknown[]; remark?: string }, user: CurrentUser) {
    const start = this.date(input.period_start); const end = this.date(input.period_end); if (end < start) throw this.invalid("INVALID_PAYROLL_PERIOD", "薪资期间无效");
    const employee = await this.prisma.employee.findFirst({ where: { id: input.employee_id, deletedAt: null } }); if (!employee) throw this.notFound("EMPLOYEE_NOT_FOUND", "员工不存在");
    const existing = await this.prisma.payrollLedger.findFirst({ where: { employeeId: employee.id, periodStart: start, periodEnd: end, deletedAt: null } }); if (existing) return this.get(existing.id);
    const sources = await this.prisma.productionPayrollSource.findMany({ where: { employeeId: employee.id, deletedAt: null, periodStart: { gte: start }, periodEnd: { lte: end } } });
    const production = sources.reduce((sum, row) => sum.plus(row.amount), new Prisma.Decimal(0));
    const row = await this.prisma.payrollLedger.create({ data: { ledgerNo: this.number("PAYROLL"), employeeId: employee.id, periodStart: start, periodEnd: end, currency: input.currency, baseSalary: this.dec(input.base_salary), productionSourceAmount: production, overtimeAmount: this.dec(input.overtime_amount), attendanceDeduction: this.dec(input.attendance_deduction), performanceAmount: this.dec(input.performance_amount), allowanceAmount: this.dec(input.allowance_amount), socialInsurance: this.dec(input.social_insurance), individualTax: this.dec(input.individual_tax), otherAdjustment: this.dec(input.other_adjustment), sourceSnapshot: sources.map((source) => ({ id: source.id, order_no: source.orderNo, wage_mode: source.wageMode, quantity: source.quantity.toString(), duration_minutes: source.durationMinutes.toString(), amount: source.amount.toString() })) as Prisma.InputJsonValue, attachment: (input.attachment ?? []) as Prisma.InputJsonValue, remark: input.remark, ...this.audit.create(user) } }); await this.audit.record("payroll_ledger.create", "payroll_ledger", user.id, row.id, { employee_id: row.employeeId, period_start: input.period_start, period_end: input.period_end, production_source_amount: production.toString() }); return row;
  }
  async confirm(id: string, user: CurrentUser) { const current = await this.get(id); if (current.status !== "draft") throw this.invalid("PAYROLL_NOT_CONFIRMABLE", "只有草稿台账可以确认"); const row = await this.prisma.payrollLedger.update({ where: { id }, data: { status: "confirmed", ...this.audit.update(user) } }); await this.audit.record("payroll_ledger.confirm", "payroll_ledger", user.id, id); return row; }
  async adjustment(id: string, input: { adjustment_type: string; effect: string; amount: string; reason: string; attachment?: unknown[]; remark?: string }, user: CurrentUser) { const ledger = await this.get(id); if (!["draft", "confirmed", "partially_paid"].includes(ledger.status)) throw this.invalid("PAYROLL_NOT_ADJUSTABLE", "当前台账不可调整"); if (!input.reason?.trim() || !["increase", "decrease"].includes(input.effect)) throw this.invalid("INVALID_PAYROLL_ADJUSTMENT", "调整方向和原因必填"); const row = await this.prisma.payrollAdjustment.create({ data: { adjustmentNo: this.number("PADJ"), ledgerId: id, employeeId: ledger.employeeId, adjustmentType: input.adjustment_type, effect: input.effect, amount: this.positive(input.amount), reason: input.reason.trim(), attachment: (input.attachment ?? []) as Prisma.InputJsonValue, remark: input.remark, ...this.audit.create(user) } }); await this.audit.record("payroll_adjustment.create", "payroll_adjustment", user.id, row.id, { ledger_id: id, amount: row.amount.toString() }); return row; }
  async postAdjustment(id: string, user: CurrentUser) { const row = await this.prisma.payrollAdjustment.findFirst({ where: { id, deletedAt: null } }); if (!row) throw this.notFound("PAYROLL_ADJUSTMENT_NOT_FOUND", "薪资调整不存在"); if (row.status !== "draft") throw this.invalid("PAYROLL_ADJUSTMENT_NOT_POSTABLE", "只有草稿调整可以过账"); return this.prisma.payrollAdjustment.update({ where: { id }, data: { status: "posted", ...this.audit.update(user) } }); }
  async reverseAdjustment(id: string, reason: string, user: CurrentUser) { if (!reason?.trim()) throw this.invalid("REVERSAL_REASON_REQUIRED", "冲销必须填写原因"); const row = await this.prisma.payrollAdjustment.findFirst({ where: { id, deletedAt: null } }); if (!row || row.status !== "posted") throw this.invalid("PAYROLL_ADJUSTMENT_NOT_REVERSIBLE", "当前调整不可冲销"); return this.prisma.payrollAdjustment.update({ where: { id }, data: { status: "reversed", remark: `${row.remark ?? ""}\n冲销：${reason}`, ...this.audit.update(user) } }); }
  async summary(id: string) { const ledger = await this.get(id); const adjustments = ledger.adjustments.filter((row) => row.status === "posted").reduce((sum, row) => sum.plus(row.effect === "increase" ? row.amount : row.amount.negated()), new Prisma.Decimal(0)); const base = ledger.baseSalary.plus(ledger.productionSourceAmount).plus(ledger.overtimeAmount).minus(ledger.attendanceDeduction).plus(ledger.performanceAmount).plus(ledger.allowanceAmount).minus(ledger.socialInsurance).minus(ledger.individualTax).plus(ledger.otherAdjustment); const net = base.plus(adjustments); const paid = ledger.allocations.filter((row) => row.status === "active").reduce((sum, row) => sum.plus(row.amount), new Prisma.Decimal(0)); return { ledger_id: id, employee_id: ledger.employeeId, period_start: ledger.periodStart, period_end: ledger.periodEnd, base_amount: base.toString(), adjustment_amount: adjustments.toString(), payable_amount: net.toString(), paid_amount: paid.toString(), outstanding_amount: net.minus(paid).toString() }; }
  async refreshStatus(client: Prisma.TransactionClient, id: string, user: CurrentUser) { const ledger = await client.payrollLedger.findFirst({ where: { id, deletedAt: null } }); if (!ledger) throw this.notFound("PAYROLL_LEDGER_NOT_FOUND", "薪资台账不存在"); const adjustments = await client.payrollAdjustment.findMany({ where: { ledgerId: id, deletedAt: null, status: "posted" } }); const base = ledger.baseSalary.plus(ledger.productionSourceAmount).plus(ledger.overtimeAmount).minus(ledger.attendanceDeduction).plus(ledger.performanceAmount).plus(ledger.allowanceAmount).minus(ledger.socialInsurance).minus(ledger.individualTax).plus(ledger.otherAdjustment); const net = base.plus(adjustments.reduce((sum, row) => sum.plus(row.effect === "increase" ? row.amount : row.amount.negated()), new Prisma.Decimal(0))); const paid = await client.salaryPaymentAllocation.aggregate({ where: { ledgerId: id, deletedAt: null, status: "active", payment: { status: "posted" } }, _sum: { amount: true } }); const amount = new Prisma.Decimal(paid._sum.amount ?? 0); const status = amount.eq(0) ? "confirmed" : amount.gte(net) ? "paid" : "partially_paid"; return client.payrollLedger.update({ where: { id }, data: { status, ...this.audit.update(user) } }); }
  private dec(value?: string) { return value ? this.nonNegative(value) : new Prisma.Decimal(0); }
  private positive(value: string) { const n = new Prisma.Decimal(value); if (!n.gt(0)) throw this.invalid("INVALID_AMOUNT", "金额必须大于零"); return n; }
  private nonNegative(value: string) { const n = new Prisma.Decimal(value); if (n.lt(0)) throw this.invalid("INVALID_AMOUNT", "金额不能为负数"); return n; }
  private date(value: string) { const d = new Date(`${value}T00:00:00.000Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(d.valueOf())) throw this.invalid("INVALID_DATE", "日期无效"); return d; }
  private number(prefix: string) { return `${prefix}-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${randomUUID().slice(0, 8).toUpperCase()}`; }
  private notFound(code: string, message: string) { return new NotFoundException({ code, message, details: [] }); }
  private invalid(code: string, message: string) { return new UnprocessableEntityException({ code, message, details: [] }); }
}
