import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";
import { PayrollLedgerService } from "./payroll-ledger.service";

type Input = { payment_date: string; amount: string; currency: string; payment_method: string; bank_reference?: string; attachment?: unknown[]; remark?: string };
type Allocation = { ledger_id: string; amount: string; remark?: string };

@Injectable()
export class SalaryPaymentService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly payroll: PayrollLedgerService) {}
  async list(status?: string) { return this.prisma.salaryPayment.findMany({ where: { deletedAt: null, ...(status ? { status } : {}) }, include: { allocations: { where: { deletedAt: null }, include: { ledger: { include: { employee: true } } } } }, orderBy: { createdAt: "desc" } }); }
  async get(id: string) { const row = await this.prisma.salaryPayment.findFirst({ where: { id, deletedAt: null }, include: { allocations: { where: { deletedAt: null }, include: { ledger: true } } } }); if (!row) throw this.notFound("SALARY_PAYMENT_NOT_FOUND", "工资付款不存在"); return row; }
  async create(input: Input, user: CurrentUser) { const amount = this.positive(input.amount); const row = await this.prisma.salaryPayment.create({ data: { paymentNo: this.number("SALARY"), paymentDate: this.date(input.payment_date), amount, currency: input.currency, paymentMethod: input.payment_method, bankReference: input.bank_reference, attachment: (input.attachment ?? []) as Prisma.InputJsonValue, remark: input.remark, ...this.audit.create(user) } }); await this.audit.record("salary_payment.create", "salary_payment", user.id, row.id, { amount: row.amount.toString() }); return row; }
  async post(id: string, allocations: Allocation[], user: CurrentUser) { const current = await this.prisma.salaryPayment.findFirst({ where: { id, deletedAt: null } }); if (!current) throw this.notFound("SALARY_PAYMENT_NOT_FOUND", "工资付款不存在"); if (current.status !== "draft") throw this.invalid("SALARY_PAYMENT_NOT_POSTABLE", "只有草稿工资付款可以过账"); const items = allocations ?? []; if (new Set(items.map((item) => item.ledger_id)).size !== items.length) throw this.invalid("DUPLICATE_SALARY_ALLOCATION", "同一付款不得重复核销同一台账"); const result = await this.prisma.$transaction(async (tx) => { let total = new Prisma.Decimal(0); for (const item of items) { const amount = this.positive(item.amount); const ledger = await tx.payrollLedger.findFirst({ where: { id: item.ledger_id, deletedAt: null } }); if (!ledger || ledger.currency !== current.currency || !["confirmed", "partially_paid"].includes(ledger.status)) throw this.invalid("PAYROLL_NOT_ALLOCATABLE", "台账不存在、币种不一致或尚未确认"); const base = ledger.baseSalary.plus(ledger.productionSourceAmount).plus(ledger.overtimeAmount).minus(ledger.attendanceDeduction).plus(ledger.performanceAmount).plus(ledger.allowanceAmount).minus(ledger.socialInsurance).minus(ledger.individualTax).plus(ledger.otherAdjustment); const adjustments = await tx.payrollAdjustment.findMany({ where: { ledgerId: ledger.id, deletedAt: null, status: "posted" } }); const net = base.plus(adjustments.reduce((sum, row) => sum.plus(row.effect === "increase" ? row.amount : row.amount.negated()), new Prisma.Decimal(0))); const paid = await tx.salaryPaymentAllocation.aggregate({ where: { ledgerId: ledger.id, deletedAt: null, status: "active", payment: { status: "posted" } }, _sum: { amount: true } }); const available = net.minus(paid._sum.amount ?? 0); if (amount.gt(available)) throw new UnprocessableEntityException({ code: "SALARY_ALLOCATION_EXCEEDED", message: "核销金额超过薪资未付余额", details: [{ available_amount: available.toString() }] }); total = total.plus(amount); await tx.salaryPaymentAllocation.create({ data: { paymentId: id, ledgerId: ledger.id, employeeId: ledger.employeeId, amount, currency: current.currency, remark: item.remark, ...this.audit.create(user) } }); } if (total.gt(current.amount)) throw new UnprocessableEntityException({ code: "SALARY_PAYMENT_ALLOCATION_EXCEEDED", message: "核销金额超过工资付款金额", details: [] }); const payment = await tx.salaryPayment.update({ where: { id }, data: { status: total.eq(0) ? "unallocated" : "posted", ...this.audit.update(user) } }); for (const item of items) await this.payroll.refreshStatus(tx, item.ledger_id, user); return payment; }); await this.audit.record("salary_payment.post", "salary_payment", user.id, id, { allocation_count: items.length }); return result; }
  async reverse(id: string, reason: string, user: CurrentUser) { if (!reason?.trim()) throw this.invalid("REVERSAL_REASON_REQUIRED", "冲销必须填写原因"); const current = await this.prisma.salaryPayment.findFirst({ where: { id, deletedAt: null }, include: { allocations: { where: { deletedAt: null, status: "active" } } } }); if (!current) throw this.notFound("SALARY_PAYMENT_NOT_FOUND", "工资付款不存在"); if (!["posted", "unallocated"].includes(current.status)) throw this.invalid("SALARY_PAYMENT_NOT_REVERSIBLE", "当前工资付款不可冲销"); const row = await this.prisma.$transaction(async (tx) => { await tx.salaryPaymentAllocation.updateMany({ where: { paymentId: id, deletedAt: null, status: "active" }, data: { status: "reversed", ...this.audit.update(user) } }); const payment = await tx.salaryPayment.update({ where: { id }, data: { status: "reversed", remark: `${current.remark ?? ""}\n冲销：${reason.trim()}`, ...this.audit.update(user) } }); for (const item of current.allocations) await this.payroll.refreshStatus(tx, item.ledgerId, user); return payment; }); await this.audit.record("salary_payment.reverse", "salary_payment", user.id, id, { reason }); return row; }
  private positive(value: string) { const n = new Prisma.Decimal(value); if (!n.gt(0)) throw this.invalid("INVALID_AMOUNT", "金额必须大于零"); return n; }
  private date(value: string) { const d = new Date(`${value}T00:00:00.000Z`); if (!/^\d{4}-\d{2}-\d{2}$/.test(value) || Number.isNaN(d.valueOf())) throw this.invalid("INVALID_PAYMENT_DATE", "付款日期无效"); return d; }
  private number(prefix: string) { return `${prefix}-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${randomUUID().slice(0, 8).toUpperCase()}`; }
  private notFound(code: string, message: string) { return new NotFoundException({ code, message, details: [] }); }
  private invalid(code: string, message: string) { return new UnprocessableEntityException({ code, message, details: [] }); }
}
