import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";
import { deduplicateAlerts, type Alert } from "./alerts.domain";

@Injectable()
export class AlertsService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async list(query: { alert_type?: string; status?: string; order_no?: string; severity?: string; page?: number; page_size?: number }) {
    const [daily, qc, negative] = await Promise.all([
      this.prisma.productionDailyAlert.findMany({ where: { deletedAt: null, status: { in: ["pending", "confirmed"] }, ...(query.alert_type ? { alertType: query.alert_type } : {}), ...(query.order_no ? { orderNo: query.order_no } : {}) }, select: { id: true, alertType: true, orderNo: true, createdAt: true } }),
      this.prisma.finishedGoodsQcRecord.findMany({ where: { deletedAt: null, conclusion: "rejected", ...(query.order_no ? { orderNo: query.order_no } : {}) }, select: { id: true, orderNo: true, createdAt: true } }),
      this.prisma.inventoryFact.groupBy({ by: ["orderNo"], where: { orderNo: { not: null } }, _sum: { quantityDelta: true } }),
    ]);
    const rows: Alert[] = [...daily.map((row) => ({ source_type: "production_daily_alert", source_id: row.id, alert_type: row.alertType, order_no: row.orderNo, severity: "high" as const, title: row.alertType === "over_order" ? "生产超单" : "生产日报差异", suggestion: "请核对日报与生产单累计数量。", status: "pending", created_at: row.createdAt })), ...qc.map((row) => ({ source_type: "finished_goods_qc", source_id: row.id, alert_type: "qc_rejected", order_no: row.orderNo, severity: "high" as const, title: "成品 QC 不合格", suggestion: "请处理不良品或重新送检。", status: "pending", created_at: row.createdAt })), ...negative.filter((row) => row._sum.quantityDelta && row._sum.quantityDelta.lt(0)).map((row) => ({ source_type: "inventory", source_id: `00000000-0000-0000-0000-${(row.orderNo ?? "00000000").slice(-12).padStart(12, "0")}`, alert_type: "inventory_delta", order_no: row.orderNo, severity: "medium" as const, title: "库存净变动为负", suggestion: "请核对出入库事实和库存不足风险。", status: "pending", created_at: new Date() }))];
    const handling = await this.prisma.alertHandling.findMany({ where: { ...(query.status ? { status: query.status } : {}) } }); const handled = new Map(handling.map((row) => [`${row.sourceType}:${row.sourceId}:${row.alertType}`, row]));
    const data = deduplicateAlerts(rows).filter((row) => !query.severity || row.severity === query.severity).map((row) => { const item = handled.get(`${row.source_type}:${row.source_id}:${row.alert_type}`); return { ...row, status: item?.status ?? row.status, handling_id: item?.id ?? null, remark: item?.remark ?? null }; }).filter((row) => !query.status || row.status === query.status); const page = query.page ?? 1; const size = Math.min(query.page_size ?? 20, 200); return { data: data.slice((page - 1) * size, page * size), total: data.length };
  }
  async handle(id: string, status: "acknowledged" | "resolved", remark: string, user: CurrentUser) { const source = await this.findSource(id); if (!source) throw new NotFoundException({ code: "ALERT_NOT_FOUND", message: "告警不存在", details: [] }); if (!remark?.trim()) throw new UnprocessableEntityException({ code: "ALERT_REMARK_REQUIRED", message: "告警处理必须填写备注", details: [] }); const row = await this.prisma.alertHandling.upsert({ where: { sourceType_sourceId_alertType: { sourceType: source.source_type, sourceId: source.source_id, alertType: source.alert_type } }, create: { sourceType: source.source_type, sourceId: source.source_id, alertType: source.alert_type, status, remark: remark.trim(), ...this.audit.create(user) }, update: { status, remark: remark.trim(), ...this.audit.update(user) } }); await this.audit.record("alert." + status, "alert_handling", user.id, row.id, { source_type: source.source_type, source_id: source.source_id, alert_type: source.alert_type, remark: remark.trim() }); return row; }
  private async findSource(id: string) { const daily = await this.prisma.productionDailyAlert.findFirst({ where: { id, deletedAt: null }, select: { id: true, alertType: true, orderNo: true } }); if (daily) return { source_type: "production_daily_alert", source_id: daily.id, alert_type: daily.alertType, order_no: daily.orderNo }; const qc = await this.prisma.finishedGoodsQcRecord.findFirst({ where: { id, deletedAt: null }, select: { id: true, orderNo: true } }); return qc ? { source_type: "finished_goods_qc", source_id: qc.id, alert_type: "qc_rejected", order_no: qc.orderNo } : null; }
}
