"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog, type ActionField } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { DataTable } from "../../components/data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPatch, apiPost } from "../../lib/api-client";

type Receivable = { id: string; sourceNo: string; orderNo?: string; amount: string; currency: string; status: string };
type Payment = { id: string; paymentNo: string; orderNo?: string; amount: string; currency: string; status: string; paymentDate: string };
type Payable = { id: string; payableNo: string; orderNo?: string; amount: string; currency: string; status: string; sourceType: string };
type PayableSource = { id: string; orderNo: string; quantity: string; amount: string; currency: string; status: string; sourceType: "raw_material_inbound" | "purchase_receipt" | "outsource_receipt"; batchSequence?: number | null; batch_sequence?: number | null; purchase_order_no?: string | null; rawMaterialInbound?: { inboundNo?: string }; purchaseReceipt?: { receiptNo?: string }; outsourceReceipt?: { id?: string }; purchaseOrder?: { purchaseOrderNo?: string }; supplier?: { name?: string } };
type Reconciliation = { id: string; orderNo: string; status: string; periodStart: string; periodEnd: string; externalBalance: string; currency: string };
type SupplierReconciliation = { id: string; reconciliationNo: string; orderNo?: string; purchaseOrder?: { purchaseOrderNo?: string }; status: string; systemBalance: string; externalBalance: string; difference: string; currency: string; supplier?: { name?: string } };
type Reference = { id: string; name: string; customerCode?: string; supplierCode?: string; orderNo?: string };
type DialogState = { title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void };
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export default function FinancePage() {
  const [receivables, setReceivables] = useState<Receivable[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [payables, setPayables] = useState<Payable[]>([]); const [payableSources, setPayableSources] = useState<PayableSource[]>([]); const [supplierPayments, setSupplierPayments] = useState<Payment[]>([]); const [reconciliations, setReconciliations] = useState<Reconciliation[]>([]); const [supplierReconciliations, setSupplierReconciliations] = useState<SupplierReconciliation[]>([]); const [customers, setCustomers] = useState<Reference[]>([]); const [suppliers, setSuppliers] = useState<Reference[]>([]); const [orders, setOrders] = useState<Reference[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState<DialogState | null>(null); const [categoryDialog, setCategoryDialog] = useState<DialogState | null>(null); const [pendingDialog, setPendingDialog] = useState<DialogState | null>(null);
  async function load() { setLoading(true); setError(""); try { const [r, p, pe, ps, ops, sp, re, sre, c, s, o] = await Promise.all([apiGet<Receivable[]>("/finance/receivable-sources"), apiGet<Payment[]>("/finance/customer-payments"), apiGet<Payable[]>("/finance/payable-entries"), apiGet<Array<PayableSource & { rawMaterialInbound?: { inboundNo?: string } }>>("/payable-sources"), apiGet<Array<PayableSource & { logisticsBatch?: { batchNo?: string } }>>("/production/outsource-logistics-batches/payable-sources"), apiGet<Payment[]>("/finance/supplier-payments"), apiGet<Reconciliation[]>("/finance/reconciliations"), apiGet<SupplierReconciliation[]>("/finance/supplier-payable-reconciliations"), apiGet<Reference[]>("/customers"), apiGet<Reference[]>("/suppliers"), apiGet<Reference[]>("/sales-orders")]); setReceivables(r.data); setPayments(p.data); setPayables(pe.data); setPayableSources([...ps.data.map((source) => ({ ...source, sourceType: source.rawMaterialInbound ? "raw_material_inbound" as const : "purchase_receipt" as const, batchSequence: source.batch_sequence ?? source.batchSequence, purchaseOrder: source.purchaseOrder ?? (source.purchase_order_no ? { purchaseOrderNo: source.purchase_order_no } : undefined) })), ...ops.data.map((source) => ({ ...source, sourceType: "outsource_receipt" as const }))]); setSupplierPayments(sp.data); setReconciliations(re.data); setSupplierReconciliations(sre.data); setCustomers(c.data); setSuppliers(s.data); setOrders(o.data); } catch (cause) { setError(messageOf(cause, "财务数据加载失败")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function action(path: string, body?: unknown, success = "操作已完成") { setError(""); setMessage(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  const customerOptions = customers.map((item) => ({ value: item.id, label: `${item.customerCode ?? ""} / ${item.name}` })); const supplierOptions = suppliers.map((item) => ({ value: item.id, label: `${item.supplierCode ?? ""} / ${item.name}` })); const orderOptions = orders.map((item) => ({ value: item.orderNo ?? item.id, label: item.orderNo ?? item.name }));
  function createCustomerPayment() { setDialog({ title: "登记收款", fields: [{ name: "customer_id", label: "客户", type: "select", required: true, options: customerOptions }, { name: "order_no", label: "订单号", type: "select", options: orderOptions }, { name: "amount", label: "收款金额", type: "number", required: true }, { name: "payment_date", label: "收款日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "payment_method", label: "收款方式", required: true, defaultValue: "银行转账" }], submit: (v) => void action("/finance/customer-payments", { customer_id: v.customer_id, order_no: v.order_no || undefined, payment_date: v.payment_date, amount: v.amount, currency: "USD", payment_method: v.payment_method }, "收款草稿已创建") }); }
  function createSupplierPayment() { setDialog({ title: "登记付款", fields: [{ name: "supplier_id", label: "供应商", type: "select", required: true, canAddCategory: true, options: supplierOptions }, { name: "order_no", label: "订单号", type: "select", options: orderOptions }, { name: "amount", label: "付款金额", type: "number", required: true }, { name: "payment_date", label: "付款日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "payment_method", label: "付款方式", required: true, defaultValue: "银行转账" }], submit: (v) => void action("/finance/supplier-payments", { supplier_id: v.supplier_id, order_no: v.order_no || undefined, payment_date: v.payment_date, amount: v.amount, currency: "CNY", payment_method: v.payment_method }, "付款草稿已创建") }); }
  function createSupplierCategory(values: Record<string, string>) { setPendingDialog(dialog); setDialog(null); setCategoryDialog({ title: "新建供应商", fields: [{ name: "supplier_code", label: "供应商编码", required: true }, { name: "name", label: "供应商名称", required: true }, { name: "contact_name", label: "联系人" }, { name: "phone", label: "联系电话" }, { name: "remark", label: "备注", type: "textarea" }], submit: async (v) => { const result = await apiPost<Reference>("/suppliers", { ...v, contact_name: v.contact_name || undefined, phone: v.phone || undefined, remark: v.remark || undefined }); setSuppliers((items) => [...items, result.data]); if (pendingDialog) setDialog({ ...pendingDialog, fields: pendingDialog.fields.map((field) => field.name === "supplier_id" ? { ...field, defaultValue: result.data.id, options: [...(field.options ?? []), { value: result.data.id, label: `${result.data.supplierCode ?? ""} / ${result.data.name}` }] } : field) }); setPendingDialog(null); setCategoryDialog(null); setMessage("供应商已创建"); } }); }
  function postCustomerPayment(item: Payment) { setDialog({ title: "收款核销", fields: [{ name: "source_id", label: "应收来源", type: "select", required: true, options: receivables.filter((source) => source.status !== "cancelled").map((source) => ({ value: source.id, label: `${source.sourceNo} / ${source.orderNo ?? "-"} / ${source.amount}` })) }, { name: "amount", label: "本次核销金额", type: "number", required: true, defaultValue: item.amount }], submit: (v) => void action(`/finance/customer-payments/${item.id}/post`, { allocations: [{ receivable_source_id: v.source_id, amount: v.amount }] }, "收款已过账并核销") }); }
  function postSupplierPayment(item: Payment) { setDialog({ title: "付款核销", fields: [{ name: "entry_id", label: "应付条目", type: "select", required: true, options: payables.filter((entry) => entry.status !== "cancelled").map((entry) => ({ value: entry.id, label: `${entry.payableNo} / ${entry.orderNo ?? "-"} / ${entry.amount}` })) }, { name: "amount", label: "本次核销金额", type: "number", required: true, defaultValue: item.amount }], submit: (v) => void action(`/finance/supplier-payments/${item.id}/post`, { allocations: [{ payable_entry_id: v.entry_id, amount: v.amount }] }, "付款已过账并核销") }); }
  function reverse(path: string) { setDialog({ title: "冲销支付", fields: [{ name: "reason", label: "冲销原因", type: "textarea", required: true }], submit: (v) => void action(path, { reason: v.reason }, "支付已冲销") }); }
  function editReceivable(item: Receivable) { setDialog({ title: "编辑应收草稿", fields: [{ name: "amount", label: "应收金额", type: "number", required: true, defaultValue: item.amount }, { name: "due_date", label: "到期日期", type: "date" }, { name: "amount_reason", label: "金额原因", type: "textarea" }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action(`/finance/receivable-sources/${item.id}`, { amount: v.amount, due_date: v.due_date || undefined, amount_reason: v.amount_reason || undefined, remark: v.remark || undefined }, "应收草稿已更新") }); }
  function cancelReceivable(item: Receivable) { setDialog({ title: `取消应收：${item.sourceNo}`, fields: [{ name: "reason", label: "取消原因", type: "textarea", required: true }], submit: (v) => void action(`/finance/receivable-sources/${item.id}/cancel`, { reason: v.reason }, "应收已取消") }); }
  function createReconciliation() { setDialog({ title: "创建对账", fields: [{ name: "order_no", label: "订单号", type: "select", required: true, options: orderOptions }, { name: "period_start", label: "期间开始", type: "date", required: true }, { name: "period_end", label: "期间结束", type: "date", required: true }, { name: "external_balance", label: "外部余额", type: "number", required: true }], submit: (v) => void action("/finance/reconciliations", { order_no: v.order_no, period_start: v.period_start, period_end: v.period_end, external_balance: v.external_balance, currency: "USD" }, "对账记录已创建") }); }
  function resolveReconciliation(id: string) { setDialog({ title: "处理对账", fields: [{ name: "remark", label: "处理备注", type: "textarea", required: true, defaultValue: "已核对" }], submit: (v) => void action(`/finance/reconciliations/${id}/resolve`, { resolution_remark: v.remark }, "对账已处理") }); }
  function receivePayableSource(source: PayableSource) { const sourceNo = source.rawMaterialInbound?.inboundNo ?? source.purchaseReceipt?.receiptNo ?? source.outsourceReceipt?.id?.slice(0, 8) ?? source.id.slice(0, 8); setDialog({ title: `接收应付：${sourceNo}`, fields: [{ name: "amount", label: "应付金额", type: "number", required: true, defaultValue: source.amount }, { name: "amount_reason", label: "金额差异原因", type: "textarea" }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action("/finance/payable-entries/from-source", { source_type: source.sourceType, source_id: source.id, amount: v.amount, amount_reason: v.amount_reason || undefined, remark: v.remark || undefined }, "应付已接收") }); }
  function createSupplierReconciliation() { setDialog({ title: "创建应付对账", fields: [{ name: "supplier_id", label: "供应商", type: "select", required: true, options: supplierOptions }, { name: "order_no", label: "订单号", type: "select", options: orderOptions }, { name: "period_start", label: "期间开始", type: "date", required: true }, { name: "period_end", label: "期间结束", type: "date", required: true }, { name: "external_balance", label: "外部应付余额", type: "number", required: true }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action("/finance/supplier-payable-reconciliations", { supplier_id: v.supplier_id, order_no: v.order_no || undefined, period_start: v.period_start, period_end: v.period_end, external_balance: v.external_balance, currency: "CNY", remark: v.remark || undefined }, "应付对账已创建") }); }
  function resolveSupplierReconciliation(id: string) { setDialog({ title: "处理应付对账差异", fields: [{ name: "remark", label: "处理说明", type: "textarea", required: true }], submit: (v) => void action(`/finance/supplier-payable-reconciliations/${id}/resolve`, { resolution_remark: v.remark }, "应付对账已处理") }); }
  function editPayment(item: Payment, kind: "customer" | "supplier") { setDialog({ title: kind === "customer" ? "编辑收款草稿" : "编辑付款草稿", fields: [{ name: "amount", label: "金额", type: "number", required: true, defaultValue: item.amount }, { name: "payment_date", label: "日期", type: "date", required: true, defaultValue: item.paymentDate.slice(0, 10) }, { name: "payment_method", label: "方式", required: true }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action(`/finance/${kind === "customer" ? "customer" : "supplier"}-payments/${item.id}`, { amount: v.amount, payment_date: v.payment_date, payment_method: v.payment_method, remark: v.remark || undefined }, "草稿已更新") }); }
  function editPayable(item: Payable) { setDialog({ title: "编辑应付草稿", fields: [{ name: "amount", label: "金额", type: "number", required: true, defaultValue: item.amount }, { name: "confirmation_date", label: "确认日期", type: "date", required: true }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action(`/finance/payable-entries/${item.id}`, { amount: v.amount, confirmation_date: v.confirmation_date || undefined, remark: v.remark || undefined }, "应付草稿已更新") }); }
  const receivableColumns: ColumnDef<Receivable>[] = [{ accessorKey: "sourceNo", header: "应收来源" }, { accessorKey: "orderNo", header: "订单号" }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "draft" ? <div className="action-row"><Button size="sm" variant="ghost" onClick={() => editReceivable(row.original)}>编辑</Button><Button size="sm" variant="secondary" onClick={() => void action(`/finance/receivable-sources/${row.original.id}/confirm`, undefined, "应收已确认")}>确认</Button><Button size="sm" variant="ghost" onClick={() => cancelReceivable(row.original)}>取消</Button></div> : null }];
  const paymentColumns = (kind: "customer" | "supplier"): ColumnDef<Payment>[] => [{ accessorKey: "paymentNo", header: kind === "customer" ? "收款单号" : "付款单号" }, { accessorKey: "paymentDate", header: "日期", cell: ({ row }) => row.original.paymentDate.slice(0, 10) }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => <>{row.original.status === "draft" && <><Button size="sm" variant="ghost" onClick={() => editPayment(row.original, kind)}>编辑</Button><Button size="sm" variant="secondary" onClick={() => kind === "customer" ? postCustomerPayment(row.original) : postSupplierPayment(row.original)}>过账/核销</Button></>}{row.original.status === "posted" && <Button size="sm" variant="destructive" onClick={() => reverse(`/finance/${kind === "customer" ? "customer" : "supplier"}-payments/${row.original.id}/reverse`)}>冲销</Button>}</> }];
  const payableColumns: ColumnDef<Payable>[] = [{ accessorKey: "payableNo", header: "应付单号" }, { accessorKey: "orderNo", header: "订单号" }, { accessorKey: "sourceType", header: "来源" }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "draft" ? <><Button size="sm" variant="ghost" onClick={() => editPayable(row.original)}>编辑</Button><Button size="sm" variant="secondary" onClick={() => void action(`/finance/payable-entries/${row.original.id}/confirm`, undefined, "应付已确认")}>确认</Button></> : null }];
  const payableSourceColumns: ColumnDef<PayableSource>[] = [{ id: "source", header: "来源批次", cell: ({ row }) => `${row.original.rawMaterialInbound?.inboundNo ?? row.original.purchaseReceipt?.receiptNo ?? row.original.outsourceReceipt?.id?.slice(0, 8) ?? "-"} / ${row.original.sourceType}` }, { id: "batch", header: "采购批次", cell: ({ row }) => row.original.batchSequence ? `第 ${row.original.batchSequence} 批` : "-" }, { accessorKey: "orderNo", header: "订单号" }, { id: "purchaseOrder", header: "采购单号", cell: ({ row }) => row.original.purchaseOrder?.purchaseOrderNo ?? "-" }, { id: "supplier", header: "供应商", cell: ({ row }) => row.original.supplier?.name ?? "-" }, { accessorKey: "quantity", header: "数量" }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "来源状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "pending_finance" ? <Button size="sm" variant="secondary" onClick={() => receivePayableSource(row.original)}>接收应付</Button> : <span>已接收</span> }];
  const reconciliationColumns: ColumnDef<Reconciliation>[] = [{ accessorKey: "orderNo", header: "订单号" }, { id: "period", header: "期间", cell: ({ row }) => `${row.original.periodStart.slice(0, 10)} 至 ${row.original.periodEnd.slice(0, 10)}` }, { id: "balance", header: "外部余额", cell: ({ row }) => `${row.original.externalBalance} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "open" ? <Button size="sm" variant="secondary" onClick={() => resolveReconciliation(row.original.id)}>处理</Button> : null }];
  const supplierReconciliationColumns: ColumnDef<SupplierReconciliation>[] = [{ accessorKey: "reconciliationNo", header: "应付对账单号" }, { id: "supplier", header: "供应商", cell: ({ row }) => row.original.supplier?.name ?? "-" }, { accessorKey: "orderNo", header: "订单号" }, { id: "purchaseOrder", header: "采购单号", cell: ({ row }) => row.original.purchaseOrder?.purchaseOrderNo ?? "-" }, { accessorKey: "systemBalance", header: "系统应付" }, { accessorKey: "externalBalance", header: "外部余额" }, { accessorKey: "difference", header: "差异" }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "difference" ? <Button size="sm" variant="secondary" onClick={() => resolveSupplierReconciliation(row.original.id)}>处理</Button> : null }];
  if (loading) return <><PageHeader title="财务" /><LoadingState /></>;
  return <>
    <PageHeader title="财务"><div className="page-actions"><Button onClick={createCustomerPayment}>登记收款</Button><Button variant="secondary" onClick={createSupplierPayment}>登记付款</Button><Button variant="secondary" onClick={createReconciliation}>创建对账</Button><Button variant="secondary" onClick={createSupplierReconciliation}>创建应付对账</Button><Link className="button button-secondary" href="/finance/salary">工资台账</Link></div></PageHeader>
    {message && <section className="panel panel-body status-success" role="status">{message}</section>}
    {error && <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>}
    <ActionDialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onAddCategory={(field, values) => { if (field.name === "supplier_id") createSupplierCategory(values); }} onSubmit={(values) => { dialog?.submit(values); setDialog(null); }} />
    <ActionDialog open={Boolean(categoryDialog)} onOpenChange={(open) => { if (!open) { setCategoryDialog(null); setPendingDialog(null); } }} title={categoryDialog?.title ?? "新建供应商"} fields={categoryDialog?.fields ?? []} onSubmit={(values) => { void categoryDialog?.submit(values); }} />
    <section className="panel"><div className="panel-heading"><h2>应收来源</h2></div><div className="panel-body"><DataTable columns={receivableColumns} data={receivables} empty={<EmptyState title="暂无应收来源" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>收款</h2></div><div className="panel-body"><DataTable columns={paymentColumns("customer")} data={payments} empty={<EmptyState title="暂无收款记录" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>原料入库应付来源</h2></div><div className="panel-body"><DataTable columns={payableSourceColumns} data={payableSources} empty={<EmptyState title="暂无待接收应付来源" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>应付条目</h2></div><div className="panel-body"><DataTable columns={payableColumns} data={payables} empty={<EmptyState title="暂无应付条目" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>付款</h2></div><div className="panel-body"><DataTable columns={paymentColumns("supplier")} data={supplierPayments} empty={<EmptyState title="暂无付款记录" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>普通对账</h2></div><div className="panel-body"><DataTable columns={reconciliationColumns} data={reconciliations} empty={<EmptyState title="暂无对账记录" />} /></div></section>
    <section className="panel"><div className="panel-heading"><h2>供应商应付对账</h2></div><div className="panel-body"><DataTable columns={supplierReconciliationColumns} data={supplierReconciliations} empty={<EmptyState title="暂无应付对账记录" />} /></div></section>
  </>;
}
