"use client";

import { useEffect, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog, type ActionField } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { DataTable } from "../../components/data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";

type Receivable = { id: string; sourceNo: string; orderNo?: string; amount: string; currency: string; status: string };
type Payment = { id: string; paymentNo: string; orderNo?: string; amount: string; currency: string; status: string; paymentDate: string };
type Payable = { id: string; payableNo: string; orderNo?: string; amount: string; currency: string; status: string; sourceType: string };
type Reconciliation = { id: string; orderNo: string; status: string; periodStart: string; periodEnd: string; externalBalance: string; currency: string };
type Reference = { id: string; name: string; customerCode?: string; supplierCode?: string; orderNo?: string };
type DialogState = { title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void };
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export default function FinancePage() {
  const [receivables, setReceivables] = useState<Receivable[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [payables, setPayables] = useState<Payable[]>([]); const [supplierPayments, setSupplierPayments] = useState<Payment[]>([]); const [reconciliations, setReconciliations] = useState<Reconciliation[]>([]); const [customers, setCustomers] = useState<Reference[]>([]); const [suppliers, setSuppliers] = useState<Reference[]>([]); const [orders, setOrders] = useState<Reference[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState<DialogState | null>(null);
  async function load() { setLoading(true); setError(""); try { const [r, p, pe, sp, re, c, s, o] = await Promise.all([apiGet<Receivable[]>("/finance/receivable-sources"), apiGet<Payment[]>("/finance/customer-payments"), apiGet<Payable[]>("/finance/payable-entries"), apiGet<Payment[]>("/finance/supplier-payments"), apiGet<Reconciliation[]>("/finance/reconciliations"), apiGet<Reference[]>("/customers"), apiGet<Reference[]>("/suppliers"), apiGet<Reference[]>("/sales-orders")]); setReceivables(r.data); setPayments(p.data); setPayables(pe.data); setSupplierPayments(sp.data); setReconciliations(re.data); setCustomers(c.data); setSuppliers(s.data); setOrders(o.data); } catch (cause) { setError(messageOf(cause, "财务数据加载失败")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function action(path: string, body?: unknown, success = "操作已完成") { setError(""); setMessage(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  const customerOptions = customers.map((item) => ({ value: item.id, label: `${item.customerCode ?? ""} / ${item.name}` })); const supplierOptions = suppliers.map((item) => ({ value: item.id, label: `${item.supplierCode ?? ""} / ${item.name}` })); const orderOptions = orders.map((item) => ({ value: item.orderNo ?? item.id, label: item.orderNo ?? item.name }));
  function createCustomerPayment() { setDialog({ title: "登记收款", fields: [{ name: "customer_id", label: "客户", type: "select", required: true, options: customerOptions }, { name: "order_no", label: "订单号", type: "select", options: orderOptions }, { name: "amount", label: "收款金额", type: "number", required: true }, { name: "payment_date", label: "收款日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "payment_method", label: "收款方式", required: true, defaultValue: "银行转账" }], submit: (v) => void action("/finance/customer-payments", { customer_id: v.customer_id, order_no: v.order_no || undefined, payment_date: v.payment_date, amount: v.amount, currency: "USD", payment_method: v.payment_method }, "收款草稿已创建") }); }
  function createSupplierPayment() { setDialog({ title: "登记付款", fields: [{ name: "supplier_id", label: "供应商", type: "select", required: true, options: supplierOptions }, { name: "order_no", label: "订单号", type: "select", options: orderOptions }, { name: "amount", label: "付款金额", type: "number", required: true }, { name: "payment_date", label: "付款日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "payment_method", label: "付款方式", required: true, defaultValue: "银行转账" }], submit: (v) => void action("/finance/supplier-payments", { supplier_id: v.supplier_id, order_no: v.order_no || undefined, payment_date: v.payment_date, amount: v.amount, currency: "CNY", payment_method: v.payment_method }, "付款草稿已创建") }); }
  function postCustomerPayment(item: Payment) { setDialog({ title: "收款核销", fields: [{ name: "source_id", label: "应收来源", type: "select", required: true, options: receivables.filter((source) => source.status !== "cancelled").map((source) => ({ value: source.id, label: `${source.sourceNo} / ${source.orderNo ?? "-"} / ${source.amount}` })) }, { name: "amount", label: "本次核销金额", type: "number", required: true, defaultValue: item.amount }], submit: (v) => void action(`/finance/customer-payments/${item.id}/post`, { allocations: [{ receivable_source_id: v.source_id, amount: v.amount }] }, "收款已过账并核销") }); }
  function postSupplierPayment(item: Payment) { setDialog({ title: "付款核销", fields: [{ name: "entry_id", label: "应付条目", type: "select", required: true, options: payables.filter((entry) => entry.status !== "cancelled").map((entry) => ({ value: entry.id, label: `${entry.payableNo} / ${entry.orderNo ?? "-"} / ${entry.amount}` })) }, { name: "amount", label: "本次核销金额", type: "number", required: true, defaultValue: item.amount }], submit: (v) => void action(`/finance/supplier-payments/${item.id}/post`, { allocations: [{ payable_entry_id: v.entry_id, amount: v.amount }] }, "付款已过账并核销") }); }
  function reverse(path: string) { setDialog({ title: "冲销支付", fields: [{ name: "reason", label: "冲销原因", type: "textarea", required: true }], submit: (v) => void action(path, { reason: v.reason }, "支付已冲销") }); }
  function createReconciliation() { setDialog({ title: "创建对账", fields: [{ name: "order_no", label: "订单号", type: "select", required: true, options: orderOptions }, { name: "period_start", label: "期间开始", type: "date", required: true }, { name: "period_end", label: "期间结束", type: "date", required: true }, { name: "external_balance", label: "外部余额", type: "number", required: true }], submit: (v) => void action("/finance/reconciliations", { order_no: v.order_no, period_start: v.period_start, period_end: v.period_end, external_balance: v.external_balance, currency: "USD" }, "对账记录已创建") }); }
  function resolveReconciliation(id: string) { setDialog({ title: "处理对账", fields: [{ name: "remark", label: "处理备注", type: "textarea", required: true, defaultValue: "已核对" }], submit: (v) => void action(`/finance/reconciliations/${id}/resolve`, { resolution_remark: v.remark }, "对账已处理") }); }
  const receivableColumns: ColumnDef<Receivable>[] = [{ accessorKey: "sourceNo", header: "应收来源" }, { accessorKey: "orderNo", header: "订单号" }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "pending_finance" ? <Button size="sm" variant="secondary" onClick={() => void action(`/finance/receivable-sources/${row.original.id}/confirm`, undefined, "应收已确认")}>确认</Button> : null }];
  const paymentColumns = (kind: "customer" | "supplier"): ColumnDef<Payment>[] => [{ accessorKey: "paymentNo", header: kind === "customer" ? "收款单号" : "付款单号" }, { accessorKey: "paymentDate", header: "日期", cell: ({ row }) => row.original.paymentDate.slice(0, 10) }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => <>{row.original.status === "draft" && <Button size="sm" variant="secondary" onClick={() => kind === "customer" ? postCustomerPayment(row.original) : postSupplierPayment(row.original)}>过账/核销</Button>}{row.original.status === "posted" && <Button size="sm" variant="destructive" onClick={() => reverse(`/finance/${kind === "customer" ? "customer" : "supplier"}-payments/${row.original.id}/reverse`)}>冲销</Button>}</> }];
  const payableColumns: ColumnDef<Payable>[] = [{ accessorKey: "payableNo", header: "应付单号" }, { accessorKey: "orderNo", header: "订单号" }, { accessorKey: "sourceType", header: "来源" }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "pending_finance" ? <Button size="sm" variant="secondary" onClick={() => void action(`/finance/payable-entries/${row.original.id}/confirm`, undefined, "应付已确认")}>确认</Button> : null }];
  const reconciliationColumns: ColumnDef<Reconciliation>[] = [{ accessorKey: "orderNo", header: "订单号" }, { id: "period", header: "期间", cell: ({ row }) => `${row.original.periodStart.slice(0, 10)} 至 ${row.original.periodEnd.slice(0, 10)}` }, { id: "balance", header: "外部余额", cell: ({ row }) => `${row.original.externalBalance} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "open" ? <Button size="sm" variant="secondary" onClick={() => resolveReconciliation(row.original.id)}>处理</Button> : null }];
  if (loading) return <><PageHeader title="财务" /><LoadingState /></>;
  return <><PageHeader title="财务"><div className="page-actions"><Button onClick={createCustomerPayment}>登记收款</Button><Button variant="secondary" onClick={createSupplierPayment}>登记付款</Button><Button variant="secondary" onClick={createReconciliation}>创建对账</Button></div></PageHeader><ActionDialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onSubmit={(values) => { dialog?.submit(values); setDialog(null); }} />{message && <section className="panel panel-body status-success" role="status">{message}</section>}{error && <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>}<section className="panel"><div className="panel-heading"><h2>应收与收款</h2></div><div className="panel-body"><DataTable columns={receivableColumns} data={receivables} empty={<EmptyState title="暂无应收来源" />} /><DataTable columns={paymentColumns("customer")} data={payments} empty={<EmptyState title="暂无收款" />} /></div></section><section className="panel"><div className="panel-heading"><h2>应付与付款</h2></div><div className="panel-body"><DataTable columns={payableColumns} data={payables} empty={<EmptyState title="暂无应付记录" />} /><DataTable columns={paymentColumns("supplier")} data={supplierPayments} empty={<EmptyState title="暂无付款" />} /></div></section><section className="panel"><div className="panel-heading"><h2>应收对账</h2></div><div className="panel-body"><DataTable columns={reconciliationColumns} data={reconciliations} empty={<EmptyState title="暂无对账记录" />} /></div></section></>;
}
