"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog, type ActionField } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "../../components/ui/sheet";
import { DataTable } from "../../components/data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { apiGet, apiPost, ApiClientError } from "../../lib/api-client";
type Customer = { id: string; customerCode: string; name: string; isActive: boolean };
type Order = { id: string; orderNo: string; productName: string; quantity: string; unit: string; status: string; customer: Customer; boms: { id: string; version: number }[] };
export default function SalesPage() { const [customers, setCustomers] = useState<Customer[]>([]); const [orders, setOrders] = useState<Order[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Order | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState(false); const fields: ActionField[] = [{ name: "order_no", label: "订单号", required: true }];
  async function load() { setLoading(true); try { const [c, o] = await Promise.all([apiGet<Customer[]>("/customers"), apiGet<Order[]>("/sales-orders")]); setCustomers(c.data); setOrders(o.data); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []); const visible = useMemo(() => orders.filter((order) => !query || `${order.orderNo} ${order.customer.name} ${order.productName} ${order.status}`.toLowerCase().includes(query.toLowerCase())), [orders, query]);
  async function createOrder(values: Record<string, string>) { const customer = customers.find((item) => item.isActive); if (!customer) { setError("请先创建启用客户"); return; } try { await apiPost("/sales-orders", { order_no: values.order_no, customer_id: customer.id, order_date: new Date().toISOString(), product_name: "待维护产品", quantity: "1", unit: "个", currency: "USD" }); setMessage("销售单已创建"); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "销售单创建失败"); } }
  async function confirm(id: string) { try { await apiPost(`/sales-orders/${id}/confirm`); setMessage("销售单已确认"); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "确认失败"); } }
  async function createBom(id: string) { try { await apiPost(`/boms/from-sales-order/${id}`, { extension_data: {} }); setMessage("BOM 草稿已创建"); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "BOM 创建失败"); } }
  const columns: ColumnDef<Order>[] = [{ accessorKey: "orderNo", header: "订单号", cell: ({ row }) => <Button variant="link" onClick={() => setSelected(row.original)}>{row.original.orderNo}</Button> }, { id: "customer", header: "客户", cell: ({ row }) => row.original.customer.name }, { accessorKey: "productName", header: "产品" }, { id: "quantity", header: "数量", cell: ({ row }) => `${row.original.quantity} ${row.original.unit}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => <>{row.original.status === "draft" && <Button size="sm" variant="secondary" onClick={() => void confirm(row.original.id)}>确认</Button>}{row.original.status === "confirmed" && !row.original.boms.length && <Button size="sm" variant="secondary" onClick={() => void createBom(row.original.id)}>创建 BOM</Button>}</> }];
  return <><PageHeader title="销售与客户" description="客户、销售单、订单号和 BOM"><Button onClick={() => setDialog(true)}>新建销售单</Button></PageHeader><ActionDialog open={dialog} onOpenChange={setDialog} title="新建销售单" fields={fields} onSubmit={(values) => void createOrder(values)} />{message && <section className="panel panel-body status-success">{message}</section>}{error ? <section className="panel"><ErrorState message={error} onRetry={() => { setError(""); void load(); }} /></section> : loading ? <LoadingState /> : <><section className="panel"><div className="panel-heading"><h2>客户池</h2><Link href="/customers">客户管理</Link></div><div className="panel-body"><span className="module-stat"><strong>{customers.length}</strong> 个客户</span></div></section><section className="panel"><div className="panel-heading"><h2>销售单</h2></div><div className="panel-body"><div className="filter-bar"><label>搜索订单、客户或状态<Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="输入关键词" /></label></div><DataTable columns={columns} data={visible} empty={<EmptyState title="暂无销售单" description="调整筛选条件或新建销售单" />} /></div></section></>}{<Sheet open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><SheetContent><SheetHeader><SheetTitle>{selected?.orderNo}</SheetTitle><SheetDescription>销售单详情与 BOM 状态</SheetDescription></SheetHeader>{selected && <div className="detail-list"><p>客户：{selected.customer.name}</p><p>产品：{selected.productName}</p><p>数量：{selected.quantity} {selected.unit}</p><p>状态：{selected.status}</p><p>BOM：{selected.boms.length ? selected.boms.map((bom) => `v${bom.version}`).join("、") : "未创建"}</p></div>}</SheetContent></Sheet>}</>;
}
