"use client";

import { useEffect, useState } from "react";
import { PageHeader } from "../../components/layout/app-shell";
import { Button } from "../../components/ui/button";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";

type PurchaseOrder = { id: string; purchaseOrderNo: string; orderNo: string; status: string; currency: string; totalAmount: string; items: Array<{ id: string; quantity: string; receipts: Array<{ quantity: string }> }> };
type Inspection = { id: string; orderNo: string; status: string; inspectedQuantity: string; acceptedQuantity: string; conditionalQuantity: string; rejectedQuantity: string };
type Inbound = { id: string; inboundNo: string; orderNo: string; quantity: string; status: string };
type PayableSource = { id: string; orderNo: string; amount: string; status: string };

export default function ProcurementPage() {
  const [orders, setOrders] = useState<PurchaseOrder[]>([]); const [inspections, setInspections] = useState<Inspection[]>([]); const [inbounds, setInbounds] = useState<Inbound[]>([]); const [payables, setPayables] = useState<PayableSource[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { setLoading(true); setError(""); try { const [po, qc, inbound, payable] = await Promise.all([apiGet<PurchaseOrder[]>("/purchase-orders"), apiGet<Inspection[]>("/incoming-inspections"), apiGet<Inbound[]>("/raw-material-inbounds"), apiGet<PayableSource[]>("/payable-sources")]); setOrders(po.data); setInspections(qc.data); setInbounds(inbound.data); setPayables(payable.data); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "采购链路数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function action(path: string, body?: unknown, success = "操作已完成") { setError(""); setMessage(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "操作失败"); } }
  function createPurchaseOrder() { const orderNo = window.prompt("请输入已确认销售单订单号"); const bomId = window.prompt("请输入已发布 BOM ID"); const supplierId = window.prompt("请输入供应商 ID"); const materialId = window.prompt("请输入物料 ID"); const unitId = window.prompt("请输入单位 ID"); if (!orderNo || !bomId || !supplierId || !materialId || !unitId) return; void action("/purchase-orders", { order_no: orderNo, bom_id: bomId, bom_version: 1, supplier_id: supplierId, purchase_date: new Date().toISOString(), currency: "USD", items: [{ material_id: materialId, unit_id: unitId, quantity: "1", unit_price: "0" }] }, "采购草稿已创建"); }
  function receive(order: PurchaseOrder) { const item = order.items[0]; if (!item) return; const quantity = window.prompt("请输入本批到货数量", "1"); if (quantity) void action(`/purchase-orders/${order.id}/items/${item.id}/receipts`, { quantity, received_date: new Date().toISOString() }, "到货记录已登记"); }
  function inspect() { const receiptId = window.prompt("请输入到货记录 ID"); const quantity = window.prompt("请输入送检数量", "1"); if (receiptId && quantity) void action("/incoming-inspections", { purchase_receipt_id: receiptId, inspected_quantity: quantity, accepted_quantity: quantity, conditional_quantity: "0", rejected_quantity: "0" }, "来料 QC 已记录"); }
  function inbound() { const inspectionId = window.prompt("请输入允许入库的 QC 记录 ID"); const quantity = window.prompt("请输入入库数量", "1"); if (inspectionId && quantity) void action("/raw-material-inbounds", { incoming_inspection_id: inspectionId, quantity, inventory_category: "raw_material" }, "原料入库草稿已创建"); }
  return <><PageHeader title="采购与来料" description="采购单、分批到货、来料 QC、原料入库与应付来源"><Button onClick={createPurchaseOrder}>新建采购单</Button></PageHeader>{message && <section className="panel panel-body status-success">{message}</section>}{error ? <section className="panel"><ErrorState message={error} onRetry={() => { void load(); }} /></section> : loading ? <LoadingState /> : <div className="workbench-grid"><section className="panel"><div className="panel-heading"><h2>采购单</h2><Button variant="secondary" onClick={inspect}>登记 QC</Button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>采购单号</th><th>订单号</th><th>状态</th><th>金额</th><th>操作</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td>{order.purchaseOrderNo}</td><td>{order.orderNo}</td><td>{order.status}</td><td>{order.totalAmount} {order.currency}</td><td>{order.status === "draft" && <Button variant="secondary" onClick={() => void action(`/purchase-orders/${order.id}/order`, undefined, "采购单已下单")}>下单</Button>}{["ordered", "partially_arrived"].includes(order.status) && <Button variant="secondary" onClick={() => receive(order)}>登记到货</Button>}</td></tr>)}</tbody></table>{!orders.length && <EmptyState title="暂无采购单" description="采购单将绑定已确认销售单与 BOM 版本" />}</div></section><section className="panel"><div className="panel-heading"><h2>来料 QC</h2><Button variant="secondary" onClick={inbound}>创建原料入库</Button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>订单号</th><th>状态</th><th>送检</th><th>合格</th><th>条件接收</th><th>不合格</th></tr></thead><tbody>{inspections.map((item) => <tr key={item.id}><td>{item.orderNo}</td><td>{item.status}</td><td>{item.inspectedQuantity}</td><td>{item.acceptedQuantity}</td><td>{item.conditionalQuantity}</td><td>{item.rejectedQuantity}</td></tr>)}</tbody></table>{!inspections.length && <EmptyState title="暂无待检批次" description="登记到货后进入来料 QC" />}</div></section><section className="panel"><div className="panel-heading"><h2>原料入库与应付来源</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>入库单号</th><th>订单号</th><th>数量</th><th>入库状态</th><th>应付来源</th></tr></thead><tbody>{inbounds.map((item) => <tr key={item.id}><td>{item.inboundNo}</td><td>{item.orderNo}</td><td>{item.quantity}</td><td>{item.status === "draft" ? <Button variant="secondary" onClick={() => void action(`/raw-material-inbounds/${item.id}/post`, undefined, "原料入库已过账")}>过账</Button> : item.status}</td><td>{payables.filter((source) => source.orderNo === item.orderNo).map((source) => `${source.amount} (${source.status})`).join(", ") || "待生成"}</td></tr>)}</tbody></table>{!inbounds.length && !payables.length && <EmptyState title="暂无入库或应付来源" description="QC 合格后创建原料入库并过账" />}</div></section></div>}</>;
}
