import { randomUUID } from "node:crypto";
import argon2 from "argon2";
import { PrismaClient } from "@prisma/client";
import { expect, test } from "playwright/test";

const databaseUrl = process.env.TEST_DATABASE_URL;
if (!databaseUrl || !/test/i.test(databaseUrl)) throw new Error("TEST_BLOCKED: TEST_DATABASE_URL must point to a dedicated test database");
const runId = randomUUID().slice(0, 8); const username = `e2e-d5-${runId}`; const password = "E2eD5Report2026"; const orderNo = `E2E-D5-${runId}`; const unitName = `件-D5-${runId}`; const operationCode = `D5-OP-${runId}`; const employeeNo = `D5-E-${runId}`; const prisma = new PrismaClient({ datasources: { db: { url: databaseUrl } } }); let userId; let salesId;

test.beforeAll(async () => {
  userId = randomUUID(); const audit = { createdBy: userId, updatedBy: userId }; const role = await prisma.role.upsert({ where: { key: "administrator" }, update: { name: "管理员", updatedBy: userId }, create: { key: "administrator", name: "管理员", ...audit } }); await prisma.user.create({ data: { id: userId, username, passwordHash: await argon2.hash(password, { type: argon2.argon2id }), displayName: "D5 浏览器测试", ...audit, roles: { create: [{ roleId: role.id }] } } });
  const unit = await prisma.unit.create({ data: { name: unitName, ...audit } }); const customer = await prisma.customer.create({ data: { customerCode: `D5-C-${runId}`, name: `D5客户-${runId}`, ...audit } }); const sales = await prisma.salesOrder.create({ data: { orderNo, customerId: customer.id, customerSnapshot: {}, orderDate: new Date(), productName: "D5雨伞", quantity: "5", unit: unit.name, currency: "USD", status: "confirmed", ...audit } }); salesId = sales.id; const version = await prisma.salesOrderVersion.create({ data: { salesOrderId: sales.id, version: 1, snapshot: {}, ...audit } }); const bom = await prisma.bom.create({ data: { orderNo, salesOrderId: sales.id, salesOrderVersionId: version.id, version: 1, status: "published", ...audit } }); const location = await prisma.productionLocation.create({ data: { name: `D5车间-${runId}`, locationType: "workshop", ...audit } }); const operation = await prisma.operationCatalog.create({ data: { operationCode, operationName: `D5缝制-${runId}`, defaultUnitId: unit.id, ...audit } }); const department = await prisma.department.create({ data: { code: `D5-D-${runId}`, name: `D5车间部-${runId}`, ...audit } }); const position = await prisma.position.create({ data: { departmentId: department.id, code: `D5-P-${runId}`, name: `D5工人-${runId}`, ...audit } }); const employee = await prisma.employee.create({ data: { employeeNo, name: `D5员工-${runId}`, departmentId: department.id, positionId: position.id, employeeType: "workshop", employmentStatus: "active", ...audit } }); await prisma.operationRate.createMany({ data: [{ employeeId: employee.id, operationId: operation.id, wageMode: "piece_rate", unitPrice: "2", effectiveFrom: new Date("2026-01-01"), ...audit }, { employeeId: employee.id, operationId: operation.id, wageMode: "time_rate", unitPrice: "3", effectiveFrom: new Date("2026-01-01"), ...audit }] }); const productionOrder = await prisma.productionOrder.create({ data: { productionOrderNo: `MO-${runId}`, orderNo, salesOrderId: sales.id, bomId: bom.id, bomVersion: 1, bomSnapshot: {}, executionMode: "in_house", executionLocationId: location.id, plannedQuantity: "5", unitId: unit.id, status: "in_progress", ...audit } }); await prisma.productionOrderOperation.create({ data: { productionOrderId: productionOrder.id, operationCatalogId: operation.id, operationNameSnapshot: operation.operationName, unitId: unit.id, sequenceNo: 1, targetQuantity: "5", ...audit } });
});

test.afterAll(async () => {
  await prisma.productionDailyAlert.deleteMany({ where: { orderNo } }); await prisma.employeeDailyReport.deleteMany({ where: { orderNo } }); await prisma.operationDailyReport.deleteMany({ where: { orderNo } }); await prisma.productionOrderOperation.deleteMany({ where: { productionOrder: { orderNo } } }); await prisma.productionOrder.deleteMany({ where: { orderNo } }); await prisma.operationRate.deleteMany({ where: { employee: { employeeNo } } }); await prisma.employee.deleteMany({ where: { employeeNo } }); await prisma.position.deleteMany({ where: { code: `D5-P-${runId}` } }); await prisma.department.deleteMany({ where: { code: `D5-D-${runId}` } }); await prisma.operationCatalog.deleteMany({ where: { operationCode } }); await prisma.productionLocation.deleteMany({ where: { name: `D5车间-${runId}` } }); await prisma.bom.deleteMany({ where: { orderNo } }); if (salesId) await prisma.salesOrderVersion.deleteMany({ where: { salesOrderId: salesId } }); await prisma.salesOrder.deleteMany({ where: { orderNo } }); await prisma.customer.deleteMany({ where: { customerCode: `D5-C-${runId}` } }); await prisma.unit.deleteMany({ where: { name: unitName } }); await prisma.session.deleteMany({ where: { userId } }); await prisma.userRole.deleteMany({ where: { userId } }); await prisma.user.deleteMany({ where: { id: userId } }); await prisma.$disconnect();
});

test("production.daily-report.workbench_completes_operation_employee_alert_and_progress_flow", async ({ page }) => {
  await page.goto("/login"); await page.getByLabel("用户名").fill(username); await page.getByLabel("密码").fill(password); await page.getByRole("button", { name: "登录" }).click(); await expect(page).toHaveURL(/\/$/, { timeout: 15_000 }); await page.goto("/production"); await expect(page.getByRole("heading", { name: "生产日报与告警" })).toBeVisible({ timeout: 15_000 });
  const orderLabel = `MO-${runId} / ${orderNo}`; const employeeLabel = `${employeeNo} / D5员工-${runId}`; const operationSelect = page.locator('select[name="production_order_operation_id"]'); const orderSelect = page.locator('select[name="production_order_id"]');
  await orderSelect.nth(0).selectOption({ label: orderLabel }); await operationSelect.nth(0).selectOption({ index: 1 }); await page.locator('input[name="completed_quantity"]').fill("6"); await page.getByRole("button", { name: "保存工序日报" }).click(); await expect(page.getByRole("status")).toContainText("工序日报已保存");
  await orderSelect.nth(1).selectOption({ label: orderLabel }); await operationSelect.nth(1).selectOption({ index: 1 }); await page.locator('select[name="employee_id"]').selectOption({ label: employeeLabel }); await page.locator('input[name="quantity"]').fill("4"); await page.getByRole("button", { name: "保存员工日报" }).click(); await expect(page.getByRole("status")).toContainText("员工日报已保存");
  await page.locator('select[name="wage_mode"]').selectOption("time_rate"); await page.locator('input[name="quantity"]').fill("2"); await page.locator('input[name="duration_minutes"]').fill("60"); await page.getByRole("button", { name: "保存员工日报" }).click(); await expect(page.getByRole("status")).toContainText("员工日报已保存"); await expect(page.locator("body")).toContainText("180"); await expect(page.locator("body")).toContainText("超单"); await expect(page.locator("body")).toContainText("差异");
  await page.getByRole("button", { name: "查看服务端累计" }).first().click(); await expect(page.locator("pre")).toContainText("over_order"); const pendingAlert = page.getByRole("row").filter({ hasText: "超单" }).first(); page.once("dialog", (dialog) => dialog.accept("已核对")); await pendingAlert.getByRole("button", { name: "确认" }).click();
});
