"use client";

import { useEffect, useMemo, useState } from "react";
import { ActionDialog, type ActionField } from "../ui/action-dialog";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { DataTable } from "../data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../feedback/states";
import { ApiClientError, apiGet, apiPost, apiRequest } from "../../lib/api-client";
import type { ColumnDef } from "@tanstack/react-table";

type Order = { id: string; productionOrderNo: string; orderNo: string; executionMode: string; status: string; operations: Array<{ id: string; operationNameSnapshot: string; targetQuantity: string; status: string }> };
type Employee = { id: string; employeeNo: string; name: string; employmentStatus: string };
type OperationReport = { id: string; version: number; orderNo: string; reportDate: string; completedQuantity: string; operationNameSnapshot: string };
type EmployeeReport = { id: string; employeeNameSnapshot: string; reportDate: string; wageMode: string; quantity: string; durationMinutes?: string; calculatedAmount: string; unitPrice: string };
type Alert = { id: string; alertType: string; status: string; orderNo: string; reportDate: string; discrepancyQuantity?: string; overOrderQuantity?: string };
type OperationForm = { production_order_id: string; production_order_operation_id: string; report_date: string; completed_quantity: string; remark?: string };
type EmployeeForm = { production_order_id: string; production_order_operation_id: string; employee_id: string; report_date: string; wage_mode: string; quantity: string; duration_minutes?: string; unit_price?: string; remark?: string };
const today = new Date().toISOString().slice(0, 10);
const key = () => `d5-${crypto.randomUUID()}`;
const errorText = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export function DailyReportsPanel() {
  const [orders, setOrders] = useState<Order[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [operationReports, setOperationReports] = useState<OperationReport[]>([]); const [employeeReports, setEmployeeReports] = useState<EmployeeReport[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [pending, setPending] = useState<{ type: "alert" | "delete"; id: string; version?: number } | null>(null); const [formDialog, setFormDialog] = useState<{ title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void } | null>(null);
  const operationOptions = orders.flatMap((order) => order.operations.filter((item) => item.status === "active").map((item) => ({ ...item, orderLabel: `${order.productionOrderNo} / ${order.orderNo}`, productionOrderId: order.id }))); const employeeOptions = employees.map((item) => ({ value: item.id, label: `${item.employeeNo} / ${item.name}` })); const orderOptions = orders.filter((item) => ["in_progress", "completed"].includes(item.status)).map((item) => ({ value: item.id, label: `${item.productionOrderNo} / ${item.orderNo}` }));
  async function load() { setLoading(true); setError(""); try { const [o, e, r, er, a] = await Promise.all([apiGet<Order[]>("/production/orders"), apiGet<Employee[]>("/production/employees"), apiGet<OperationReport[]>("/production/operation-reports"), apiGet<EmployeeReport[]>("/production/employee-reports"), apiGet<Alert[]>("/production/daily-alerts")]); setOrders(o.data.filter((item) => item.executionMode === "in_house")); setEmployees(e.data.filter((item) => item.employmentStatus === "active")); setOperationReports(r.data); setEmployeeReports(er.data); setAlerts(a.data); } catch (cause) { setError(errorText(cause, "日报数据加载失败")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function run(action: () => Promise<unknown>, success: string) { setError(""); try { await action(); setMessage(success); await load(); } catch (cause) { setError(errorText(cause, "操作失败")); } }
  function submitPending(values: Record<string, string>) { if (!pending) return; const action = pending.type === "alert" ? () => apiPost(`/production/daily-alerts/${pending.id}/confirm`, { remark: values.remark }) : () => apiRequest(`/production/operation-reports/${pending.id}`, { method: "DELETE", body: JSON.stringify({ reason: values.reason, expected_version: pending.version }) }); void run(action, pending.type === "alert" ? "告警已确认" : "工序日报已逻辑删除"); setPending(null); }
  function openOperationReport() { setFormDialog({ title: "工序日报", fields: [{ name: "production_order_id", label: "生产单", type: "select", required: true, options: orderOptions }, { name: "production_order_operation_id", label: "工序", type: "select", required: true, options: operationOptions.map((item) => ({ value: item.id, label: `${item.orderLabel} / ${item.operationNameSnapshot}` })) }, { name: "report_date", label: "生产日期", type: "date", required: true, defaultValue: today }, { name: "completed_quantity", label: "完成量", type: "number", required: true }, { name: "remark", label: "备注", type: "textarea" }], submit: (values) => void run(() => apiPost("/production/operation-reports", { ...values, idempotency_key: key() }), "工序日报已保存") }); }
  function openEmployeeReport() { setFormDialog({ title: "员工日报", fields: [{ name: "production_order_id", label: "生产单", type: "select", required: true, options: orderOptions }, { name: "production_order_operation_id", label: "工序", type: "select", required: true, options: operationOptions.map((item) => ({ value: item.id, label: `${item.orderLabel} / ${item.operationNameSnapshot}` })) }, { name: "employee_id", label: "员工", type: "select", required: true, options: employeeOptions }, { name: "report_date", label: "生产日期", type: "date", required: true, defaultValue: today }, { name: "wage_mode", label: "计薪方式", type: "select", required: true, options: [{ value: "piece_rate", label: "计件" }, { value: "time_rate", label: "计时" }] }, { name: "quantity", label: "件数", type: "number", required: true }, { name: "duration_minutes", label: "时长（分钟）", type: "number" }, { name: "unit_price", label: "单价", type: "number" }, { name: "remark", label: "备注", type: "textarea" }], submit: (values) => void run(() => apiPost("/production/employee-reports", { ...values, idempotency_key: key() }), "员工日报已保存") }); }
  const operationColumns: ColumnDef<OperationReport>[] = [{ accessorKey: "reportDate", header: "日期", cell: ({ row }) => row.original.reportDate.slice(0, 10) }, { accessorKey: "orderNo", header: "订单号" }, { accessorKey: "operationNameSnapshot", header: "工序" }, { accessorKey: "completedQuantity", header: "完成量" }, { id: "actions", header: "操作", cell: ({ row }) => <Button variant="destructive" size="sm" onClick={async () => { try { await apiGet(`/production/operation-reports/${row.original.id}/impact-preview`); setPending({ type: "delete", id: row.original.id, version: row.original.version }); } catch (cause) { setError(errorText(cause, "影响预览失败")); } }}>删除</Button> }];
  const employeeColumns: ColumnDef<EmployeeReport>[] = [{ accessorKey: "reportDate", header: "日期", cell: ({ row }) => row.original.reportDate.slice(0, 10) }, { accessorKey: "employeeNameSnapshot", header: "员工" }, { accessorKey: "wageMode", header: "计薪方式" }, { accessorKey: "quantity", header: "件数" }, { accessorKey: "durationMinutes", header: "分钟" }, { accessorKey: "calculatedAmount", header: "参考金额" }];
  if (loading) return <section className="panel"><LoadingState /></section>; if (error && !orders.length) return <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>;
  const alertColumns: ColumnDef<Alert>[] = [{ id: "date", header: "日期", cell: ({ row }) => row.original.reportDate.slice(0, 10) }, { accessorKey: "orderNo", header: "订单号" }, { id: "type", header: "类型", cell: ({ row }) => row.original.alertType === "over_order" ? `超单 ${row.original.overOrderQuantity ?? ""}` : `差异 ${row.original.discrepancyQuantity ?? ""}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "pending" ? <Button variant="secondary" size="sm" onClick={() => setPending({ type: "alert", id: row.original.id })}>确认</Button> : null }];
  return <section className="panel daily-report-panel"><ActionDialog open={Boolean(pending)} onOpenChange={(open) => { if (!open) setPending(null); }} title={pending?.type === "delete" ? "删除工序日报" : "处理告警"} fields={pending?.type === "delete" ? [{ name: "reason", label: "删除原因", type: "textarea", required: true }] : [{ name: "remark", label: "告警处理备注", type: "textarea", required: true }]} onSubmit={submitPending} /><ActionDialog open={Boolean(formDialog)} onOpenChange={(open) => { if (!open) setFormDialog(null); }} title={formDialog?.title ?? "日报"} fields={formDialog?.fields ?? []} onSubmit={(values) => { formDialog?.submit(values); setFormDialog(null); }} /><div className="panel-heading"><h2>生产日报与告警</h2><div className="page-actions"><Button onClick={openOperationReport}>工序日报</Button><Button variant="secondary" onClick={openEmployeeReport}>员工日报</Button><Button variant="ghost" onClick={() => void load()}>刷新</Button></div></div>{message && <p className="status-success panel-body">{message}</p>}{error && <p className="status-error panel-body">{error}</p>}<div className="panel-body"><h3>工序日报历史</h3><DataTable columns={operationColumns} data={operationReports} empty={<EmptyState title="暂无工序日报" />} /><h3>员工日报历史</h3><DataTable columns={employeeColumns} data={employeeReports} empty={<EmptyState title="暂无员工日报" />} /><h3>日报告警</h3><DataTable columns={alertColumns} data={alerts} empty={<EmptyState title="暂无告警" />} /></div></section>;
}
