"use client";
import { useEffect, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { ActionDialog, type ActionField } from "../ui/action-dialog";
import { Button } from "../ui/button";
import { DataTable } from "../data/data-table";
import { EmptyState } from "../feedback/states";
import { ApiClientError, apiGet, apiPost, apiRequest } from "../../lib/api-client";
type Batch = { id: string; batchNo: string; orderNo: string; status: string; plannedQuantity: string; dispatchedQuantity: string; receipts: Array<{ quantity: string; status: string }> };
type Transfer = { id: string; transferNo: string; transferType: string; orderNo: string; quantity: string; status: string };
function messageOf(cause: unknown, fallback: string) { return cause instanceof ApiClientError ? cause.message : fallback; }
export function OutsourceLogisticsPanel() {
  const [batches, setBatches] = useState<Batch[]>([]); const [transfers, setTransfers] = useState<Transfer[]>([]); const [dialog, setDialog] = useState<{ title: string; fields: ActionField[]; submit: (v: Record<string, string>) => void } | null>(null); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { try { const [b, r, s] = await Promise.all([apiGet<Batch[]>("/production/outsource-logistics-batches"), apiGet<Transfer[]>("/production/outsource-logistics-batches/returns"), apiGet<Transfer[]>("/production/outsource-logistics-batches/direct-shipments")]); setBatches(b.data); setTransfers([...r.data, ...s.data]); } catch (cause) { setError(messageOf(cause, "外加工数据加载失败")); } }
  useEffect(() => { void load(); }, []); async function run(action: () => Promise<unknown>, success: string) { try { await action(); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  function open(title: string, fields: ActionField[], submit: (v: Record<string, string>) => Promise<unknown>) { setDialog({ title, fields, submit: (v) => void run(() => submit(v), `${title}已完成`) }); }
  function createBatch() { open("新建直发批次", [{ name: "production_order_id", label: "外加工生产单 ID", required: true }, { name: "purchase_order_item_id", label: "采购明细 ID", required: true }, { name: "planned_quantity", label: "计划直发数量", type: "number", required: true }], (v) => apiPost("/production/outsource-logistics-batches", v)); }
  function dispatch(batch: Batch) { open("登记直发", [{ name: "quantity", label: "直发数量", type: "number", required: true }, { name: "dispatch_date", label: "直发日期", type: "date", required: true }, { name: "proof_remark", label: "交接凭据", required: true }], (v) => apiPost(`/production/outsource-logistics-batches/${batch.id}/dispatch`, v)); }
  function receipt(batch: Batch) { open("登记签收", [{ name: "quantity", label: "签收数量", type: "number", required: true }, { name: "receipt_date", label: "签收日期", type: "date", required: true }, { name: "receiver_name", label: "签收人" }, { name: "proof_remark", label: "签收凭据", required: true }, { name: "idempotency_key", label: "幂等键", required: true, defaultValue: `web-${Date.now()}` }], (v) => apiPost(`/production/outsource-logistics-batches/${batch.id}/receipts`, v)); }
  function transfer(title: string, path: string) { open(title, [{ name: "production_order_id", label: "生产单 ID", required: true }, { name: "logistics_batch_id", label: "直发批次 ID", required: path.endsWith("/material"), placeholder: "原料回厂时填写" }, { name: "material_id", label: "物料 ID", required: path.endsWith("/material"), placeholder: "原料回厂时填写" }, { name: "unit_id", label: "单位 ID", required: true }, { name: "product_description", label: "成品/物料描述", required: path !== "/production/outsource-logistics-batches/returns/material" }, { name: "quantity", label: "数量", type: "number", required: true }, { name: "transfer_date", label: "日期", type: "date", required: true }, { name: "shipment_date", label: "装柜日期", type: "date", required: path.endsWith("/direct-shipments") }, { name: "logistics_reference", label: "物流参考号", required: path.endsWith("/direct-shipments") }], (v) => apiPost(path, v)); }
  const batchColumns: ColumnDef<Batch>[] = [{ accessorKey: "batchNo", header: "批次" }, { accessorKey: "orderNo", header: "订单号" }, { accessorKey: "status", header: "状态" }, { id: "quantity", header: "计划/直发", cell: ({ row }) => `${row.original.plannedQuantity} / ${row.original.dispatchedQuantity}` }, { id: "actions", header: "操作", cell: ({ row }) => <><Button size="sm" variant="secondary" onClick={() => dispatch(row.original)}>直发</Button><Button size="sm" variant="secondary" onClick={() => receipt(row.original)}>签收</Button>{row.original.status === "draft" && <Button size="sm" variant="destructive" onClick={() => void run(() => apiRequest(`/production/outsource-logistics-batches/${row.original.id}`, { method: "DELETE" }), "草稿已删除")}>删除</Button>}</> }];
  const transferColumns: ColumnDef<Transfer>[] = [{ accessorKey: "transferNo", header: "编号" }, { accessorKey: "orderNo", header: "订单号" }, { accessorKey: "transferType", header: "类型" }, { accessorKey: "quantity", header: "数量" }, { accessorKey: "status", header: "状态" }];
  return <section className="panel outsource-panel"><ActionDialog open={Boolean(dialog)} onOpenChange={(openState) => { if (!openState) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onSubmit={(values) => { dialog?.submit(values); setDialog(null); }} /><div className="panel-heading"><h2>外加工交接</h2><div className="page-actions"><Button onClick={createBatch}>新建直发批次</Button><Button variant="secondary" onClick={() => transfer("余料回厂", "/production/outsource-logistics-batches/returns/material")}>余料回厂</Button><Button variant="secondary" onClick={() => transfer("成品回厂", "/production/outsource-logistics-batches/returns/finished-goods")}>成品回厂</Button><Button variant="secondary" onClick={() => transfer("直装柜", "/production/outsource-logistics-batches/direct-shipments")}>直装柜</Button></div></div>{message && <p className="status-success panel-body">{message}</p>}{error && <p className="status-error panel-body">{error}</p>}<div className="panel-body"><DataTable columns={batchColumns} data={batches} empty={<EmptyState title="暂无外加工批次" />} /><h3>回厂与直装柜</h3><DataTable columns={transferColumns} data={transfers} empty={<EmptyState title="暂无回厂或直装柜记录" />} /></div></section>;
}
