import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

type Input = { order_no: string; bom_id: string; bom_version: number; production_order_type?: string; parent_production_order_id?: string; execution_mode: string; execution_location_id: string; planned_quantity: string; unit_id: string; product_specification?: string; production_process_note?: string; planned_started_on?: string; delivery_due_on?: string; remark?: string };
const TYPES = new Set(["standard", "supplement", "rework", "split"]);
@Injectable()
export class ProductionOrdersService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async list(orderNo?: string) { return this.prisma.productionOrder.findMany({ where: { deletedAt: null, ...(orderNo ? { orderNo } : {}) }, include: { executionLocation: true, unit: true, bom: true }, orderBy: { updatedAt: "desc" } }); }
  async get(id: string) { const item = await this.prisma.productionOrder.findFirst({ where: { id, deletedAt: null }, include: { executionLocation: true, unit: true, bom: true, parent: true, children: true } }); if (!item) throw new NotFoundException({ code: "PRODUCTION_ORDER_NOT_FOUND", message: "生产单不存在", details: [] }); return item; }
  async create(input: Input, user: CurrentUser) {
    const refs = await this.refs(input);
    const type = input.production_order_type ?? "standard";
    if (!TYPES.has(type)) throw new UnprocessableEntityException({ code: "INVALID_PRODUCTION_ORDER_TYPE", message: "生产单类型无效", details: [] });
    if (Number(input.planned_quantity) <= 0 || !Number.isFinite(Number(input.planned_quantity))) throw new UnprocessableEntityException({ code: "INVALID_PLANNED_QUANTITY", message: "计划数量必须大于零", details: [] });
    if (type !== "standard") { if (!input.parent_production_order_id) throw new UnprocessableEntityException({ code: "PARENT_PRODUCTION_ORDER_REQUIRED", message: "补单、返工单和拆分单必须关联父生产单", details: [] }); const parent = await this.get(input.parent_production_order_id); if (parent.orderNo !== refs.order.orderNo) throw new UnprocessableEntityException({ code: "PARENT_ORDER_MISMATCH", message: "父生产单必须属于同一订单", details: [] }); }
    const number = `MO-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${randomUUID().slice(0, 8).toUpperCase()}`;
    const created = await this.prisma.productionOrder.create({ data: { productionOrderNo: number, orderNo: refs.order.orderNo, salesOrderId: refs.order.id, bomId: refs.bom.id, bomVersion: refs.bom.version, bomSnapshot: refs.bom as unknown as Prisma.InputJsonValue, productionOrderType: type, parentProductionOrderId: input.parent_production_order_id, executionMode: input.execution_mode, executionLocationId: input.execution_location_id, plannedQuantity: input.planned_quantity, unitId: input.unit_id, productSpecification: input.product_specification, productionProcessNote: input.production_process_note, plannedStartedOn: input.planned_started_on ? new Date(input.planned_started_on) : undefined, deliveryDueOn: input.delivery_due_on ? new Date(input.delivery_due_on) : undefined, remark: input.remark, ...this.audit.create(user) } });
    await this.audit.record("production_order.create", "production_order", user.id, created.id, { order_no: created.orderNo, production_order_no: number }); return this.get(created.id);
  }
  async update(id: string, input: Partial<Input>, user: CurrentUser) { const current = await this.get(id); if (current.status !== "draft") throw new UnprocessableEntityException({ code: "PRODUCTION_ORDER_NOT_EDITABLE", message: "只有草稿生产单可编辑", details: [] }); if (input.execution_mode || input.execution_location_id) await this.validateLocation(input.execution_mode ?? current.executionMode, input.execution_location_id ?? current.executionLocationId); if (input.planned_quantity !== undefined && Number(input.planned_quantity) <= 0) throw new UnprocessableEntityException({ code: "INVALID_PLANNED_QUANTITY", message: "计划数量必须大于零", details: [] }); const result = await this.prisma.productionOrder.update({ where: { id }, data: { ...(input.execution_mode === undefined ? {} : { executionMode: input.execution_mode }), ...(input.execution_location_id === undefined ? {} : { executionLocationId: input.execution_location_id }), ...(input.planned_quantity === undefined ? {} : { plannedQuantity: input.planned_quantity }), ...(input.product_specification === undefined ? {} : { productSpecification: input.product_specification }), ...(input.production_process_note === undefined ? {} : { productionProcessNote: input.production_process_note }), ...(input.planned_started_on === undefined ? {} : { plannedStartedOn: new Date(input.planned_started_on) }), ...(input.delivery_due_on === undefined ? {} : { deliveryDueOn: new Date(input.delivery_due_on) }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }); await this.audit.record("production_order.update", "production_order", user.id, id, { order_no: current.orderNo }); return result; }
  async delete(id: string, user: CurrentUser) { const item = await this.get(id); if (item.status !== "draft") throw new UnprocessableEntityException({ code: "PRODUCTION_ORDER_NOT_DELETABLE", message: "只有草稿生产单可删除", details: [] }); const result = await this.prisma.productionOrder.update({ where: { id }, data: this.audit.softDelete(user) }); await this.audit.record("production_order.delete", "production_order", user.id, id, { order_no: item.orderNo }); return result; }
  private async refs(input: Input) { const [order, bom, location, unit] = await Promise.all([this.prisma.salesOrder.findFirst({ where: { orderNo: input.order_no, status: "confirmed", deletedAt: null } }), this.prisma.bom.findFirst({ where: { id: input.bom_id, version: input.bom_version, orderNo: input.order_no, status: "published", deletedAt: null } }), this.prisma.productionLocation.findFirst({ where: { id: input.execution_location_id, isActive: true, deletedAt: null } }), this.prisma.unit.findFirst({ where: { id: input.unit_id, isActive: true, deletedAt: null } })]); if (!order) throw new NotFoundException({ code: "SALES_ORDER_NOT_CONFIRMED", message: "销售单不存在或未确认", details: [] }); if (!bom) throw new NotFoundException({ code: "BOM_NOT_FOUND", message: "BOM 不存在、版本不匹配或未发布", details: [] }); if (!location) throw new NotFoundException({ code: "PRODUCTION_LOCATION_NOT_FOUND", message: "生产地点不存在或已停用", details: [] }); if (!unit) throw new NotFoundException({ code: "UNIT_NOT_FOUND", message: "单位不存在或已停用", details: [] }); await this.validateLocation(input.execution_mode, location.id, location.locationType); return { order, bom, location, unit }; }
  private async validateLocation(mode: string, locationId: string, knownType?: string) { if (mode !== "in_house" && mode !== "outsourced") throw new UnprocessableEntityException({ code: "INVALID_EXECUTION_MODE", message: "执行方式无效", details: [] }); const type = knownType ?? (await this.prisma.productionLocation.findFirst({ where: { id: locationId, deletedAt: null } }))?.locationType; if ((mode === "in_house" && type !== "workshop") || (mode === "outsourced" && type !== "outsource_site")) throw new UnprocessableEntityException({ code: "EXECUTION_LOCATION_MISMATCH", message: "执行方式与生产地点类型不匹配", details: [] }); }
}
