import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

type User = CurrentUser;
@Injectable()
export class ProductionMasterDataService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}

  listDepartments() { return this.prisma.department.findMany({ where: { deletedAt: null }, include: { positions: { where: { deletedAt: null }, orderBy: { name: "asc" } } }, orderBy: { code: "asc" } }); }
  async createDepartment(input: { code: string; name: string; remark?: string }, user: User) { return this.write("department", () => this.prisma.department.create({ data: { code: input.code, name: input.name, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateDepartment(id: string, input: Partial<{ code: string; name: string; remark: string }>, user: User) { await this.requireDepartment(id); return this.write("department", () => this.prisma.department.update({ where: { id }, data: { ...input, ...this.audit.update(user) } }), user, id); }
  async setDepartmentActive(id: string, active: boolean, user: User) { await this.requireDepartment(id); const item = await this.prisma.department.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "department.activate" : "department.deactivate", "department", user.id, id); return item; }

  listPositions(departmentId?: string) { return this.prisma.position.findMany({ where: { deletedAt: null, ...(departmentId ? { departmentId } : {}) }, include: { department: true }, orderBy: { name: "asc" } }); }
  async createPosition(input: { department_id: string; code: string; name: string; remark?: string }, user: User) { await this.requireActiveDepartment(input.department_id); return this.write("position", () => this.prisma.position.create({ data: { departmentId: input.department_id, code: input.code, name: input.name, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updatePosition(id: string, input: Partial<{ department_id: string; code: string; name: string; remark: string }>, user: User) { await this.requirePosition(id); if (input.department_id) await this.requireActiveDepartment(input.department_id); return this.write("position", () => this.prisma.position.update({ where: { id }, data: { ...(input.department_id === undefined ? {} : { departmentId: input.department_id }), ...(input.code === undefined ? {} : { code: input.code }), ...(input.name === undefined ? {} : { name: input.name }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setPositionActive(id: string, active: boolean, user: User) { await this.requirePosition(id); const item = await this.prisma.position.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "position.activate" : "position.deactivate", "position", user.id, id); return item; }

  listEmployees() { return this.prisma.employee.findMany({ where: { deletedAt: null }, include: { department: true, position: true }, orderBy: { employeeNo: "asc" } }); }
  async createEmployee(input: { employee_no: string; name: string; department_id: string; position_id: string; employee_type: string; user_id?: string; hired_on?: string; left_on?: string; remark?: string }, user: User) { await this.requireOrganization(input.department_id, input.position_id); return this.write("employee", () => this.prisma.employee.create({ data: { employeeNo: input.employee_no, name: input.name, departmentId: input.department_id, positionId: input.position_id, employeeType: input.employee_type, userId: input.user_id, hiredOn: input.hired_on ? new Date(input.hired_on) : undefined, leftOn: input.left_on ? new Date(input.left_on) : undefined, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateEmployee(id: string, input: Partial<{ employee_no: string; name: string; department_id: string; position_id: string; employee_type: string; user_id: string; hired_on: string; left_on: string; remark: string }>, user: User) { const employee = await this.requireEmployee(id); if (input.department_id || input.position_id) await this.requireOrganization(input.department_id ?? employee.departmentId, input.position_id ?? employee.positionId); return this.write("employee", () => this.prisma.employee.update({ where: { id }, data: { ...(input.employee_no === undefined ? {} : { employeeNo: input.employee_no }), ...(input.name === undefined ? {} : { name: input.name }), ...(input.department_id === undefined ? {} : { departmentId: input.department_id }), ...(input.position_id === undefined ? {} : { positionId: input.position_id }), ...(input.employee_type === undefined ? {} : { employeeType: input.employee_type }), ...(input.user_id === undefined ? {} : { userId: input.user_id }), ...(input.hired_on === undefined ? {} : { hiredOn: new Date(input.hired_on) }), ...(input.left_on === undefined ? {} : { leftOn: new Date(input.left_on) }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setEmployeeActive(id: string, active: boolean, user: User) { await this.requireEmployee(id); const item = await this.prisma.employee.update({ where: { id }, data: { employmentStatus: active ? "active" : "inactive", ...this.audit.update(user) } }); await this.audit.record(active ? "employee.activate" : "employee.deactivate", "employee", user.id, id); return item; }

  listLocations() { return this.prisma.productionLocation.findMany({ where: { deletedAt: null }, orderBy: [{ locationType: "asc" }, { name: "asc" }] }); }
  async createLocation(input: { name: string; location_type: string; contact_name?: string; contact_phone?: string; address?: string; remark?: string }, user: User) { this.assertLocationType(input.location_type); return this.write("production_location", () => this.prisma.productionLocation.create({ data: { name: input.name, locationType: input.location_type, contactName: input.contact_name, contactPhone: input.contact_phone, address: input.address, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateLocation(id: string, input: Partial<{ name: string; location_type: string; contact_name: string; contact_phone: string; address: string; remark: string }>, user: User) { await this.requireLocation(id); if (input.location_type) this.assertLocationType(input.location_type); return this.write("production_location", () => this.prisma.productionLocation.update({ where: { id }, data: { ...(input.name === undefined ? {} : { name: input.name }), ...(input.location_type === undefined ? {} : { locationType: input.location_type }), ...(input.contact_name === undefined ? {} : { contactName: input.contact_name }), ...(input.contact_phone === undefined ? {} : { contactPhone: input.contact_phone }), ...(input.address === undefined ? {} : { address: input.address }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setLocationActive(id: string, active: boolean, user: User) { await this.requireLocation(id); const item = await this.prisma.productionLocation.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "production_location.activate" : "production_location.deactivate", "production_location", user.id, id); return item; }

  private async write(kind: string, action: () => Promise<any>, user: User, id?: string) { try { const result = await action(); await this.audit.record(`${kind}.${id ? "update" : "create"}`, kind, user.id, id ?? result.id); return result; } catch (error) { if (error && typeof error === "object" && "code" in error && error.code === "P2002") throw new ConflictException({ code: "PRODUCTION_MASTER_DATA_CONFLICT", message: "编码、名称或有效关系已存在", details: [] }); throw error; } }
  private async requireDepartment(id: string) { const item = await this.prisma.department.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "DEPARTMENT_NOT_FOUND", message: "部门不存在", details: [] }); return item; }
  private async requireActiveDepartment(id: string) { const item = await this.prisma.department.findFirst({ where: { id, deletedAt: null, isActive: true } }); if (!item) throw new NotFoundException({ code: "DEPARTMENT_NOT_FOUND", message: "部门不存在或已停用", details: [] }); return item; }
  private async requirePosition(id: string) { const item = await this.prisma.position.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "POSITION_NOT_FOUND", message: "岗位不存在", details: [] }); return item; }
  private async requireEmployee(id: string) { const item = await this.prisma.employee.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "EMPLOYEE_NOT_FOUND", message: "员工不存在", details: [] }); return item; }
  private async requireLocation(id: string) { const item = await this.prisma.productionLocation.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "PRODUCTION_LOCATION_NOT_FOUND", message: "生产地点不存在", details: [] }); return item; }
  private async requireOrganization(departmentId?: string, positionId?: string) { if (!departmentId || !positionId) return; const position = await this.prisma.position.findFirst({ where: { id: positionId, departmentId, deletedAt: null, isActive: true }, include: { department: true } }); if (!position?.department.isActive) throw new NotFoundException({ code: "ORGANIZATION_NOT_FOUND", message: "部门或岗位不存在、已停用或不匹配", details: [] }); }
  private assertLocationType(value: string) { if (value !== "workshop" && value !== "outsource_site") throw new ConflictException({ code: "INVALID_LOCATION_TYPE", message: "生产地点类型无效", details: [] }); }
}
