import { ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import * as XLSX from "xlsx";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

type User = CurrentUser;
@Injectable()
export class ProductionMasterDataService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}

  listDepartments(includeDeleted = false) { return this.prisma.department.findMany({ where: includeDeleted ? {} : { deletedAt: null }, include: { positions: { where: includeDeleted ? {} : { deletedAt: null }, orderBy: { name: "asc" } }, _count: { select: { positions: true, employees: true } } }, orderBy: { code: "asc" } }); }
  async createDepartment(input: { code: string; name: string; remark?: string }, user: User) { return this.write("department", () => this.prisma.department.create({ data: { code: input.code, name: input.name, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateDepartment(id: string, input: Partial<{ code: string; name: string; remark: string }>, user: User) { await this.requireDepartment(id); return this.write("department", () => this.prisma.department.update({ where: { id }, data: { ...input, ...this.audit.update(user) } }), user, id); }
  async setDepartmentActive(id: string, active: boolean, user: User) { await this.requireDepartment(id); const item = await this.prisma.department.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "department.activate" : "department.deactivate", "department", user.id, id); return item; }
  async deleteDepartment(id: string, user: User) { const item = await this.requireDepartment(id); const [employees, positions] = await Promise.all([this.prisma.employee.count({ where: { departmentId: id, deletedAt: null } }), this.prisma.position.count({ where: { departmentId: id, deletedAt: null } })]); if (employees || positions) throw new ConflictException({ code: "DEPARTMENT_IN_USE", message: "部门仍被员工或岗位引用，请先停用或迁移关联数据", details: [{ employees, positions }] }); return this.prisma.department.update({ where: { id }, data: { deletedAt: new Date(), deletedBy: user.id, isActive: false, updatedBy: user.id } }); }
  async restoreDepartment(id: string, user: User) { const item = await this.prisma.department.findFirst({ where: { id, deletedAt: { not: null } } }); if (!item) throw new NotFoundException({ code: "DEPARTMENT_NOT_DELETED", message: "部门不存在或未删除", details: [] }); return this.prisma.department.update({ where: { id }, data: { deletedAt: null, deletedBy: null, isActive: true, updatedBy: user.id } }); }

  listPositions(departmentId?: string) { return this.prisma.position.findMany({ where: { deletedAt: null, ...(departmentId ? { departmentId } : {}) }, include: { department: true }, orderBy: { name: "asc" } }); }
  async createPosition(input: { department_id: string; code: string; name: string; remark?: string }, user: User) { await this.requireActiveDepartment(input.department_id); return this.write("position", () => this.prisma.position.create({ data: { departmentId: input.department_id, code: input.code, name: input.name, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updatePosition(id: string, input: Partial<{ department_id: string; code: string; name: string; remark: string }>, user: User) { await this.requirePosition(id); if (input.department_id) await this.requireActiveDepartment(input.department_id); return this.write("position", () => this.prisma.position.update({ where: { id }, data: { ...(input.department_id === undefined ? {} : { departmentId: input.department_id }), ...(input.code === undefined ? {} : { code: input.code }), ...(input.name === undefined ? {} : { name: input.name }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setPositionActive(id: string, active: boolean, user: User) { await this.requirePosition(id); const item = await this.prisma.position.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "position.activate" : "position.deactivate", "position", user.id, id); return item; }
  async deletePosition(id: string, user: User) { await this.requirePosition(id); const employees = await this.prisma.employee.count({ where: { positionId: id, deletedAt: null } }); if (employees) throw new ConflictException({ code: "POSITION_IN_USE", message: "岗位仍被员工引用，请先停用或迁移关联员工", details: [{ employees }] }); return this.prisma.position.update({ where: { id }, data: { deletedAt: new Date(), deletedBy: user.id, isActive: false, updatedBy: user.id } }); }
  async restorePosition(id: string, user: User) { const item = await this.prisma.position.findFirst({ where: { id, deletedAt: { not: null } } }); if (!item) throw new NotFoundException({ code: "POSITION_NOT_DELETED", message: "岗位不存在或未删除", details: [] }); await this.requireActiveDepartment(item.departmentId); return this.prisma.position.update({ where: { id }, data: { deletedAt: null, deletedBy: null, isActive: true, updatedBy: user.id } }); }

  listEmployees(filters: { query?: string; employment_status?: string; department_id?: string; position_id?: string; employee_type?: string; hired_from?: string; hired_to?: string; left_from?: string; left_to?: string; has_user?: string } = {}) { const query = filters.query?.trim(); return this.prisma.employee.findMany({ where: { deletedAt: null, ...(query ? { OR: [{ employeeNo: { contains: query, mode: "insensitive" } }, { name: { contains: query, mode: "insensitive" } }] } : {}), ...(filters.employment_status ? { employmentStatus: filters.employment_status } : {}), ...(filters.department_id ? { departmentId: filters.department_id } : {}), ...(filters.position_id ? { positionId: filters.position_id } : {}), ...(filters.employee_type ? { employeeType: filters.employee_type } : {}), ...(filters.has_user === "true" ? { userId: { not: null } } : filters.has_user === "false" ? { userId: null } : {}), ...(filters.hired_from || filters.hired_to ? { hiredOn: { ...(filters.hired_from ? { gte: new Date(filters.hired_from) } : {}), ...(filters.hired_to ? { lte: new Date(filters.hired_to) } : {}) } } : {}), ...(filters.left_from || filters.left_to ? { leftOn: { ...(filters.left_from ? { gte: new Date(filters.left_from) } : {}), ...(filters.left_to ? { lte: new Date(filters.left_to) } : {}) } } : {}) }, include: { department: true, position: true }, orderBy: [{ employeeNo: "asc" }, { name: "asc" }] }); }
  async exportEmployees(filters: Parameters<ProductionMasterDataService["listEmployees"]>[0]) { const rows = await this.listEmployees(filters); const userIds = rows.flatMap((row) => row.userId ? [row.userId] : []); const users = userIds.length ? await this.prisma.user.findMany({ where: { id: { in: userIds }, deletedAt: null }, select: { id: true, username: true } }) : []; const usernames = new Map(users.map((user) => [user.id, user.username])); const data = rows.map((row) => ({ "工号": row.employeeNo, "姓名": row.name, "员工类型": row.employeeType === "workshop" ? "车间" : row.employeeType === "non_workshop" ? "非车间" : row.employeeType, "员工状态": row.employmentStatus === "active" ? "在职" : row.employmentStatus === "left" ? "离职" : row.employmentStatus === "inactive" ? "停用" : row.employmentStatus, "入职日期": row.hiredOn ? row.hiredOn.toISOString().slice(0, 10) : "", "离职日期": row.leftOn ? row.leftOn.toISOString().slice(0, 10) : "", "部门编码": row.department.code, "部门名称": row.department.name, "岗位编码": row.position.code, "岗位名称": row.position.name, "绑定系统用户名": row.userId ? usernames.get(row.userId) ?? "" : "", "员工备注": row.remark ?? "", "创建时间": row.createdAt.toISOString().replace("T", " ").slice(0, 19), "更新时间": row.updatedAt.toISOString().replace("T", " ").slice(0, 19) })); const sheet = XLSX.utils.json_to_sheet(data); sheet["!cols"] = Object.keys(data[0] ?? { "工号": "" }).map(() => ({ wch: 18 })); const book = XLSX.utils.book_new(); XLSX.utils.book_append_sheet(book, sheet, "员工名单"); return XLSX.write(book, { type: "buffer", bookType: "xlsx" }); }
  async createEmployee(input: { employee_no: string; name: string; department_id: string; position_id: string; employee_type: string; user_id?: string; hired_on?: string; left_on?: string; remark?: string }, user: User) { await this.requireOrganization(input.department_id, input.position_id); this.assertEmployeeType(input.employee_type); return this.write("employee", () => this.prisma.employee.create({ data: { employeeNo: input.employee_no, name: input.name, departmentId: input.department_id, positionId: input.position_id, employeeType: input.employee_type, userId: input.user_id, hiredOn: input.hired_on ? new Date(input.hired_on) : undefined, leftOn: input.left_on ? new Date(input.left_on) : undefined, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateEmployee(id: string, input: Partial<{ employee_no: string; name: string; department_id: string; position_id: string; employee_type: string; user_id: string; hired_on: string; left_on: string; remark: string }>, user: User) { const employee = await this.requireEmployee(id); if (input.department_id || input.position_id) await this.requireOrganization(input.department_id ?? employee.departmentId, input.position_id ?? employee.positionId); if (input.employee_type) this.assertEmployeeType(input.employee_type); return this.write("employee", () => this.prisma.employee.update({ where: { id }, data: { ...(input.employee_no === undefined ? {} : { employeeNo: input.employee_no }), ...(input.name === undefined ? {} : { name: input.name }), ...(input.department_id === undefined ? {} : { departmentId: input.department_id }), ...(input.position_id === undefined ? {} : { positionId: input.position_id }), ...(input.employee_type === undefined ? {} : { employeeType: input.employee_type }), ...(input.user_id === undefined ? {} : { userId: input.user_id }), ...(input.hired_on === undefined ? {} : { hiredOn: new Date(input.hired_on) }), ...(input.left_on === undefined ? {} : { leftOn: new Date(input.left_on) }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setEmployeeActive(id: string, active: boolean, user: User) { await this.requireEmployee(id); const item = await this.prisma.employee.update({ where: { id }, data: { employmentStatus: active ? "active" : "inactive", ...this.audit.update(user) } }); await this.audit.record(active ? "employee.activate" : "employee.deactivate", "employee", user.id, id); return item; }
  async setEmployeeLeft(id: string, leftOn: string, user: User) { const employee = await this.requireEmployee(id); if (employee.employmentStatus !== "active") throw new ConflictException({ code: "EMPLOYEE_NOT_ACTIVE", message: "只有在职员工可以办理离职", details: [] }); const item = await this.prisma.employee.update({ where: { id }, data: { employmentStatus: "left", leftOn: new Date(leftOn), ...this.audit.update(user) } }); await this.audit.record("employee.leave", "employee", user.id, id, { left_on: leftOn }); return item; }

  listLocations() { return this.prisma.productionLocation.findMany({ where: { deletedAt: null }, orderBy: [{ locationType: "asc" }, { name: "asc" }] }); }
  async createLocation(input: { name: string; location_type: string; contact_name?: string; contact_phone?: string; address?: string; remark?: string }, user: User) { this.assertLocationType(input.location_type); return this.write("production_location", () => this.prisma.productionLocation.create({ data: { name: input.name, locationType: input.location_type, contactName: input.contact_name, contactPhone: input.contact_phone, address: input.address, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateLocation(id: string, input: Partial<{ name: string; location_type: string; contact_name: string; contact_phone: string; address: string; remark: string }>, user: User) { await this.requireLocation(id); if (input.location_type) this.assertLocationType(input.location_type); return this.write("production_location", () => this.prisma.productionLocation.update({ where: { id }, data: { ...(input.name === undefined ? {} : { name: input.name }), ...(input.location_type === undefined ? {} : { locationType: input.location_type }), ...(input.contact_name === undefined ? {} : { contactName: input.contact_name }), ...(input.contact_phone === undefined ? {} : { contactPhone: input.contact_phone }), ...(input.address === undefined ? {} : { address: input.address }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setLocationActive(id: string, active: boolean, user: User) { await this.requireLocation(id); const item = await this.prisma.productionLocation.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "production_location.activate" : "production_location.deactivate", "production_location", user.id, id); return item; }

  listOperations() { return this.prisma.operationCatalog.findMany({ where: { deletedAt: null }, include: { defaultUnit: true }, orderBy: { operationName: "asc" } }); }
  async createOperation(input: { operation_code?: string; operation_name: string; default_unit_id?: string; remark?: string }, user: User) { if (input.default_unit_id) await this.requireActiveUnit(input.default_unit_id); return this.write("operation_catalog", () => this.prisma.operationCatalog.create({ data: { operationCode: input.operation_code, operationName: input.operation_name, defaultUnitId: input.default_unit_id, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateOperation(id: string, input: Partial<{ operation_code: string; operation_name: string; default_unit_id: string; remark: string }>, user: User) { await this.requireOperation(id); if (input.default_unit_id) await this.requireActiveUnit(input.default_unit_id); return this.write("operation_catalog", () => this.prisma.operationCatalog.update({ where: { id }, data: { ...(input.operation_code === undefined ? {} : { operationCode: input.operation_code }), ...(input.operation_name === undefined ? {} : { operationName: input.operation_name }), ...(input.default_unit_id === undefined ? {} : { defaultUnitId: input.default_unit_id }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }
  async setOperationActive(id: string, active: boolean, user: User) { await this.requireOperation(id); const item = await this.prisma.operationCatalog.update({ where: { id }, data: { isActive: active, ...this.audit.update(user) } }); await this.audit.record(active ? "operation_catalog.activate" : "operation_catalog.deactivate", "operation_catalog", user.id, id); return item; }
  listRates(employeeId?: string, operationId?: string) { return this.prisma.operationRate.findMany({ where: { deletedAt: null, ...(employeeId ? { employeeId } : {}), ...(operationId ? { operationId } : {}) }, include: { employee: true, operation: true }, orderBy: [{ effectiveFrom: "desc" }, { createdAt: "desc" }] }); }
  async createRate(input: { employee_id: string; operation_id: string; wage_mode: string; unit_price: string; effective_from: string; effective_to?: string; remark?: string }, user: User) { this.assertWageMode(input.wage_mode); await this.requireActiveEmployee(input.employee_id); await this.requireActiveOperation(input.operation_id); this.assertRateDates(input.effective_from, input.effective_to); await this.ensureRateNoOverlap(input, undefined); return this.write("operation_rate", () => this.prisma.operationRate.create({ data: { employeeId: input.employee_id, operationId: input.operation_id, wageMode: input.wage_mode, unitPrice: input.unit_price, effectiveFrom: new Date(input.effective_from), effectiveTo: input.effective_to ? new Date(input.effective_to) : undefined, remark: input.remark, ...this.audit.create(user) } }), user); }
  async updateRate(id: string, input: Partial<{ employee_id: string; operation_id: string; wage_mode: string; unit_price: string; effective_from: string; effective_to: string; remark: string }>, user: User) { const current = await this.requireRate(id); const merged = { employee_id: input.employee_id ?? current.employeeId, operation_id: input.operation_id ?? current.operationId, wage_mode: input.wage_mode ?? current.wageMode, unit_price: input.unit_price ?? current.unitPrice.toString(), effective_from: input.effective_from ?? current.effectiveFrom.toISOString().slice(0, 10), effective_to: input.effective_to ?? (current.effectiveTo ? current.effectiveTo.toISOString().slice(0, 10) : undefined), remark: input.remark }; this.assertWageMode(merged.wage_mode); await this.requireActiveEmployee(merged.employee_id); await this.requireActiveOperation(merged.operation_id); this.assertRateDates(merged.effective_from, merged.effective_to); await this.ensureRateNoOverlap(merged, id); return this.write("operation_rate", () => this.prisma.operationRate.update({ where: { id }, data: { employeeId: merged.employee_id, operationId: merged.operation_id, wageMode: merged.wage_mode, unitPrice: merged.unit_price, effectiveFrom: new Date(merged.effective_from), effectiveTo: merged.effective_to ? new Date(merged.effective_to) : null, ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }), user, id); }

  private async write(kind: string, action: () => Promise<any>, user: User, id?: string) { try { const result = await action(); await this.audit.record(`${kind}.${id ? "update" : "create"}`, kind, user.id, id ?? result.id); return result; } catch (error) { if (error && typeof error === "object" && "code" in error && error.code === "P2002") throw new ConflictException({ code: "PRODUCTION_MASTER_DATA_CONFLICT", message: "编码、名称或有效关系已存在", details: [] }); throw error; } }
  private async requireDepartment(id: string) { const item = await this.prisma.department.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "DEPARTMENT_NOT_FOUND", message: "部门不存在", details: [] }); return item; }
  private async requireActiveDepartment(id: string) { const item = await this.prisma.department.findFirst({ where: { id, deletedAt: null, isActive: true } }); if (!item) throw new NotFoundException({ code: "DEPARTMENT_NOT_FOUND", message: "部门不存在或已停用", details: [] }); return item; }
  private async requirePosition(id: string) { const item = await this.prisma.position.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "POSITION_NOT_FOUND", message: "岗位不存在", details: [] }); return item; }
  private async requireEmployee(id: string) { const item = await this.prisma.employee.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "EMPLOYEE_NOT_FOUND", message: "员工不存在", details: [] }); return item; }
  private async requireLocation(id: string) { const item = await this.prisma.productionLocation.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "PRODUCTION_LOCATION_NOT_FOUND", message: "生产地点不存在", details: [] }); return item; }
  private async requireOperation(id: string) { const item = await this.prisma.operationCatalog.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "OPERATION_NOT_FOUND", message: "工序不存在", details: [] }); return item; }
  private async requireRate(id: string) { const item = await this.prisma.operationRate.findFirst({ where: { id, deletedAt: null } }); if (!item) throw new NotFoundException({ code: "OPERATION_RATE_NOT_FOUND", message: "工序计价不存在", details: [] }); return item; }
  private async requireActiveEmployee(id: string) { const item = await this.prisma.employee.findFirst({ where: { id, deletedAt: null, employmentStatus: "active" } }); if (!item) throw new NotFoundException({ code: "EMPLOYEE_NOT_FOUND", message: "员工不存在或已停用", details: [] }); return item; }
  private async requireActiveOperation(id: string) { const item = await this.prisma.operationCatalog.findFirst({ where: { id, deletedAt: null, isActive: true } }); if (!item) throw new NotFoundException({ code: "OPERATION_NOT_FOUND", message: "工序不存在或已停用", details: [] }); return item; }
  private async requireActiveUnit(id: string) { const item = await this.prisma.unit.findFirst({ where: { id, deletedAt: null, isActive: true } }); if (!item) throw new NotFoundException({ code: "UNIT_NOT_FOUND", message: "单位不存在或已停用", details: [] }); return item; }
  private assertWageMode(value: string) { if (value !== "piece_rate" && value !== "time_rate") throw new ConflictException({ code: "INVALID_WAGE_MODE", message: "计薪方式无效", details: [] }); }
  private assertEmployeeType(value: string) { if (value !== "workshop" && value !== "non_workshop") throw new ConflictException({ code: "INVALID_EMPLOYEE_TYPE", message: "员工类型仅允许车间和非车间", details: [] }); }
  private assertRateDates(from: string, to?: string) { if (to && new Date(to) < new Date(from)) throw new ConflictException({ code: "INVALID_RATE_DATE_RANGE", message: "计价失效日期不能早于生效日期", details: [] }); if (Number.isNaN(new Date(from).getTime())) throw new ConflictException({ code: "INVALID_RATE_DATE_RANGE", message: "计价生效日期无效", details: [] }); }
  private async ensureRateNoOverlap(input: { employee_id: string; operation_id: string; wage_mode: string; effective_from: string; effective_to?: string }, excludeId?: string) { const records = await this.prisma.operationRate.findMany({ where: { employeeId: input.employee_id, operationId: input.operation_id, wageMode: input.wage_mode, deletedAt: null, ...(excludeId ? { NOT: { id: excludeId } } : {}) } }); const from = new Date(input.effective_from).getTime(); const to = input.effective_to ? new Date(input.effective_to).getTime() : Number.POSITIVE_INFINITY; if (records.some((record) => from <= (record.effectiveTo?.getTime() ?? Number.POSITIVE_INFINITY) && record.effectiveFrom.getTime() <= to)) throw new ConflictException({ code: "OPERATION_RATE_OVERLAP", message: "同一员工、工序和计薪方式的生效日期不能重叠", details: [] }); }
  private async requireOrganization(departmentId?: string, positionId?: string) { if (!departmentId || !positionId) return; const position = await this.prisma.position.findFirst({ where: { id: positionId, departmentId, deletedAt: null, isActive: true }, include: { department: true } }); if (!position?.department.isActive) throw new NotFoundException({ code: "ORGANIZATION_NOT_FOUND", message: "部门或岗位不存在、已停用或不匹配", details: [] }); }
  private assertLocationType(value: string) { if (value !== "workshop" && value !== "outsource_site") throw new ConflictException({ code: "INVALID_LOCATION_TYPE", message: "生产地点类型无效", details: [] }); }
}
