import { Injectable, NotFoundException, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { AuditService } from "../../platform/audit/audit.service";
import type { CurrentUser } from "../../platform/auth/auth.service";
import { PrismaService } from "../../platform/database/prisma.service";

type Input = { order_no: string; bom_id: string; bom_version: number; production_order_type?: string; parent_production_order_id?: string; execution_mode: string; execution_location_id: string; planned_quantity: string; unit_id: string; product_specification?: string; production_process_note?: string; planned_started_on?: string; delivery_due_on?: string; remark?: string };
const TYPES = new Set(["standard", "supplement", "rework", "split"]);
@Injectable()
export class ProductionOrdersService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService) {}
  async list(orderNo?: string) { return this.prisma.productionOrder.findMany({ where: { deletedAt: null, ...(orderNo ? { orderNo } : {}) }, include: { executionLocation: true, unit: true, bom: true, operations: { where: { deletedAt: null }, orderBy: { sequenceNo: "asc" } } }, orderBy: { updatedAt: "desc" } }); }
  async get(id: string) { const item = await this.prisma.productionOrder.findFirst({ where: { id, deletedAt: null }, include: { executionLocation: true, unit: true, bom: true, parent: true, children: true, operations: { where: { deletedAt: null }, include: { operationCatalog: true, unit: true }, orderBy: { sequenceNo: "asc" } } } }); if (!item) throw new NotFoundException({ code: "PRODUCTION_ORDER_NOT_FOUND", message: "生产单不存在", details: [] }); return item; }
  async create(input: Input, user: CurrentUser) {
    const refs = await this.refs(input);
    const type = input.production_order_type ?? "standard";
    if (!TYPES.has(type)) throw new UnprocessableEntityException({ code: "INVALID_PRODUCTION_ORDER_TYPE", message: "生产单类型无效", details: [] });
    if (Number(input.planned_quantity) <= 0 || !Number.isFinite(Number(input.planned_quantity))) throw new UnprocessableEntityException({ code: "INVALID_PLANNED_QUANTITY", message: "计划数量必须大于零", details: [] });
    if (type !== "standard") { if (!input.parent_production_order_id) throw new UnprocessableEntityException({ code: "PARENT_PRODUCTION_ORDER_REQUIRED", message: "补单、返工单和拆分单必须关联父生产单", details: [] }); const parent = await this.get(input.parent_production_order_id); if (parent.orderNo !== refs.order.orderNo) throw new UnprocessableEntityException({ code: "PARENT_ORDER_MISMATCH", message: "父生产单必须属于同一订单", details: [] }); }
    const number = `MO-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${randomUUID().slice(0, 8).toUpperCase()}`;
    const created = await this.prisma.productionOrder.create({ data: { productionOrderNo: number, orderNo: refs.order.orderNo, salesOrderId: refs.order.id, bomId: refs.bom.id, bomVersion: refs.bom.version, bomSnapshot: refs.bom as unknown as Prisma.InputJsonValue, productionOrderType: type, parentProductionOrderId: input.parent_production_order_id, executionMode: input.execution_mode, executionLocationId: input.execution_location_id, plannedQuantity: input.planned_quantity, unitId: input.unit_id, productSpecification: input.product_specification, productionProcessNote: input.production_process_note, plannedStartedOn: input.planned_started_on ? new Date(input.planned_started_on) : undefined, deliveryDueOn: input.delivery_due_on ? new Date(input.delivery_due_on) : undefined, remark: input.remark, ...this.audit.create(user) } });
    await this.audit.record("production_order.create", "production_order", user.id, created.id, { order_no: created.orderNo, production_order_no: number }); return this.get(created.id);
  }
  async update(id: string, input: Partial<Input>, user: CurrentUser) { const current = await this.get(id); if (current.status !== "draft") throw new UnprocessableEntityException({ code: "PRODUCTION_ORDER_NOT_EDITABLE", message: "只有草稿生产单可编辑", details: [] }); if (input.execution_mode || input.execution_location_id) await this.validateLocation(input.execution_mode ?? current.executionMode, input.execution_location_id ?? current.executionLocationId); if (input.planned_quantity !== undefined && Number(input.planned_quantity) <= 0) throw new UnprocessableEntityException({ code: "INVALID_PLANNED_QUANTITY", message: "计划数量必须大于零", details: [] }); const result = await this.prisma.productionOrder.update({ where: { id }, data: { ...(input.execution_mode === undefined ? {} : { executionMode: input.execution_mode }), ...(input.execution_location_id === undefined ? {} : { executionLocationId: input.execution_location_id }), ...(input.planned_quantity === undefined ? {} : { plannedQuantity: input.planned_quantity }), ...(input.product_specification === undefined ? {} : { productSpecification: input.product_specification }), ...(input.production_process_note === undefined ? {} : { productionProcessNote: input.production_process_note }), ...(input.planned_started_on === undefined ? {} : { plannedStartedOn: new Date(input.planned_started_on) }), ...(input.delivery_due_on === undefined ? {} : { deliveryDueOn: new Date(input.delivery_due_on) }), ...(input.remark === undefined ? {} : { remark: input.remark }), ...this.audit.update(user) } }); await this.audit.record("production_order.update", "production_order", user.id, id, { order_no: current.orderNo }); return result; }
  async delete(id: string, user: CurrentUser) { const item = await this.get(id); if (item.status !== "draft") throw new UnprocessableEntityException({ code: "PRODUCTION_ORDER_NOT_DELETABLE", message: "只有草稿生产单可删除", details: [] }); const result = await this.prisma.productionOrder.update({ where: { id }, data: this.audit.softDelete(user) }); await this.audit.record("production_order.delete", "production_order", user.id, id, { order_no: item.orderNo }); return result; }
  async addOperation(id: string, input: { operation_id: string; sequence_no: number; target_quantity: string; unit_id?: string }, user: CurrentUser) { const order = await this.get(id); if (Number(input.target_quantity) <= 0 || !Number.isInteger(input.sequence_no) || input.sequence_no <= 0) throw new UnprocessableEntityException({ code: "INVALID_OPERATION_TARGET", message: "工序顺序和目标数量必须有效", details: [] }); const operation = await this.prisma.operationCatalog.findFirst({ where: { id: input.operation_id, isActive: true, deletedAt: null } }); if (!operation) throw new NotFoundException({ code: "OPERATION_NOT_FOUND", message: "工序不存在或已停用", details: [] }); const unitId = input.unit_id ?? operation.defaultUnitId ?? order.unitId; const unit = await this.prisma.unit.findFirst({ where: { id: unitId, isActive: true, deletedAt: null } }); if (!unit) throw new NotFoundException({ code: "UNIT_NOT_FOUND", message: "工序单位不存在或已停用", details: [] }); const result = await this.prisma.productionOrderOperation.create({ data: { productionOrderId: id, operationCatalogId: operation.id, operationNameSnapshot: operation.operationName, unitId: unit.id, sequenceNo: input.sequence_no, targetQuantity: input.target_quantity, ...this.audit.create(user) } }); await this.audit.record("production_order_operation.create", "production_order_operation", user.id, result.id, { order_no: order.orderNo, production_order_id: id }); return result; }
  async updateOperation(id: string, operationId: string, input: { sequence_no?: number; target_quantity?: string; unit_id?: string }, user: CurrentUser) { const current = await this.requireOperation(id, operationId); if (input.target_quantity !== undefined && Number(input.target_quantity) <= 0) throw new UnprocessableEntityException({ code: "INVALID_OPERATION_TARGET", message: "目标数量必须大于零", details: [] }); if (input.sequence_no !== undefined && (!Number.isInteger(input.sequence_no) || input.sequence_no <= 0)) throw new UnprocessableEntityException({ code: "INVALID_OPERATION_TARGET", message: "工序顺序必须为正整数", details: [] }); if (input.unit_id !== undefined) { const unit = await this.prisma.unit.findFirst({ where: { id: input.unit_id, isActive: true, deletedAt: null } }); if (!unit) throw new NotFoundException({ code: "UNIT_NOT_FOUND", message: "工序单位不存在或已停用", details: [] }); } const result = await this.prisma.productionOrderOperation.update({ where: { id: operationId }, data: { ...(input.sequence_no === undefined ? {} : { sequenceNo: input.sequence_no }), ...(input.target_quantity === undefined ? {} : { targetQuantity: input.target_quantity }), ...(input.unit_id === undefined ? {} : { unitId: input.unit_id }), ...this.audit.update(user) } }); await this.audit.record("production_order_operation.update", "production_order_operation", user.id, operationId, { order_no: current.productionOrder.orderNo }); return result; }
  async cancelOperation(id: string, operationId: string, reason: string, user: CurrentUser) { const current = await this.requireOperation(id, operationId); if (!reason?.trim()) throw new UnprocessableEntityException({ code: "CANCELLATION_REASON_REQUIRED", message: "取消工序必须填写原因", details: [] }); const result = await this.prisma.productionOrderOperation.update({ where: { id: operationId }, data: { status: "cancelled", cancellationReason: reason, ...this.audit.update(user) } }); await this.audit.record("production_order_operation.cancel", "production_order_operation", user.id, operationId, { order_no: current.productionOrder.orderNo, reason }); return result; }
  async transition(id: string, target: string, reason: string | undefined, user: CurrentUser) { const current = await this.get(id); const allowed: Record<string, string[]> = { draft: ["in_progress"], in_progress: ["paused", "completed"], paused: ["in_progress"], completed: ["closed", "in_progress"] }; if (!allowed[current.status]?.includes(target)) throw new UnprocessableEntityException({ code: "INVALID_STATE_TRANSITION", message: "生产单状态转换不允许", details: [] }); if (!reason?.trim()) throw new UnprocessableEntityException({ code: "TRANSITION_REASON_REQUIRED", message: "状态转换必须填写原因", details: [] }); if (target === "in_progress" && current.status === "draft" && current.executionMode === "in_house" && !current.operations.some((operation) => operation.status === "active")) throw new UnprocessableEntityException({ code: "PRODUCTION_OPERATIONS_REQUIRED", message: "厂内生产单启动前至少需要一道有效工序", details: [] }); const dates = target === "in_progress" && current.status === "draft" ? { startedOn: new Date() } : target === "completed" ? { completedOn: new Date() } : {}; const result = await this.prisma.productionOrder.update({ where: { id }, data: { status: target, ...dates, ...this.audit.update(user) } }); await this.audit.record("production_order.transition", "production_order", user.id, id, { order_no: current.orderNo, from: current.status, to: target, reason }); return result; }
  async impactPreview(id: string) { const order = await this.get(id); const [purchaseOrders, auditEvents] = await Promise.all([this.prisma.purchaseOrder.findMany({ where: { orderNo: order.orderNo, deletedAt: null }, select: { id: true, purchaseOrderNo: true, status: true } }), this.prisma.auditEvent.count({ where: { entityType: "production_order", entityId: id } })]); return { order_no: order.orderNo, production_order_no: order.productionOrderNo, status: order.status, bom_id: order.bomId, bom_version: order.bomVersion, operations: order.operations.map((operation) => ({ id: operation.id, name: operation.operationNameSnapshot, status: operation.status, target_quantity: operation.targetQuantity })), downstream: { purchase_orders: purchaseOrders, purchase_order_count: purchaseOrders.length, inventory_facts: "本批尚未建立", payroll: "本批尚未建立" }, audit_event_count: auditEvents, warning: purchaseOrders.length ? "该订单已有采购事实，生产单变更需人工复核" : null }; }
  async auditEvents(id: string) { await this.get(id); return this.prisma.auditEvent.findMany({ where: { entityType: "production_order", entityId: id }, orderBy: { createdAt: "desc" } }); }
  private async refs(input: Input) { const [order, location, unit] = await Promise.all([this.prisma.salesOrder.findFirst({ where: { orderNo: input.order_no, status: "confirmed", deletedAt: null } }), this.prisma.productionLocation.findFirst({ where: { id: input.execution_location_id, isActive: true, deletedAt: null } }), this.prisma.unit.findFirst({ where: { id: input.unit_id, isActive: true, deletedAt: null } })]); if (!order) throw new NotFoundException({ code: "SALES_ORDER_NOT_CONFIRMED", message: "销售单不存在或未确认", details: [] }); const bom = await this.prisma.bom.findFirst({ where: { id: input.bom_id, salesOrderId: order.id, orderNo: input.order_no, deletedAt: null } }); if (!bom) throw new NotFoundException({ code: "BOM_NOT_FOUND", message: "BOM表不存在或不属于该销售单", details: [] }); if (!location) throw new NotFoundException({ code: "PRODUCTION_LOCATION_NOT_FOUND", message: "生产地点不存在或已停用", details: [] }); if (!unit) throw new NotFoundException({ code: "UNIT_NOT_FOUND", message: "单位不存在或已停用", details: [] }); await this.validateLocation(input.execution_mode, location.id, location.locationType); return { order, bom, location, unit }; }
  private async validateLocation(mode: string, locationId: string, knownType?: string) { if (mode !== "in_house" && mode !== "outsourced") throw new UnprocessableEntityException({ code: "INVALID_EXECUTION_MODE", message: "执行方式无效", details: [] }); const type = knownType ?? (await this.prisma.productionLocation.findFirst({ where: { id: locationId, deletedAt: null } }))?.locationType; if ((mode === "in_house" && type !== "workshop") || (mode === "outsourced" && type !== "outsource_site")) throw new UnprocessableEntityException({ code: "EXECUTION_LOCATION_MISMATCH", message: "执行方式与生产地点类型不匹配", details: [] }); }
  private async requireOperation(orderId: string, operationId: string) { const item = await this.prisma.productionOrderOperation.findFirst({ where: { id: operationId, productionOrderId: orderId, deletedAt: null }, include: { productionOrder: true } }); if (!item) throw new NotFoundException({ code: "PRODUCTION_OPERATION_NOT_FOUND", message: "生产单工序不存在", details: [] }); return item; }
}
