"use client";

import { useEffect, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog, type ActionField } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { DataTable } from "../../components/data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";

type Employee = { id: string; employeeNo: string; name: string; employeeType: string; employmentStatus: string; department?: { name: string }; position?: { name: string } };
type RecordItem = { id: string; employeeId: string; attendanceDate?: string; attendanceType?: string; periodStart?: string; periodEnd?: string; score?: string; grade?: string };
type Ledger = { id: string; employeeId: string; periodStart: string; periodEnd: string; payableAmount: string; status: string; currency: string };
type Payment = { id: string; paymentNo: string; paymentDate: string; amount: string; currency: string; status: string };
type DialogState = { title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void };
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export default function HrPage() {
  const [employees, setEmployees] = useState<Employee[]>([]); const [attendance, setAttendance] = useState<RecordItem[]>([]); const [performance, setPerformance] = useState<RecordItem[]>([]); const [ledgers, setLedgers] = useState<Ledger[]>([]); const [payments, setPayments] = useState<Payment[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState<DialogState | null>(null);
  async function load() { setLoading(true); setError(""); try { const [e, a, p, l, s] = await Promise.all([apiGet<Employee[]>("/production/employees"), apiGet<RecordItem[]>("/hr/attendance-records"), apiGet<RecordItem[]>("/hr/performance-records"), apiGet<Ledger[]>("/hr/payroll-ledgers"), apiGet<Payment[]>("/hr/salary-payments")]); setEmployees(e.data); setAttendance(a.data); setPerformance(p.data); setLedgers(l.data); setPayments(s.data); } catch (cause) { setError(messageOf(cause, "人事数据加载失败")); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function action(path: string, body?: unknown, success = "操作已完成") { setError(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  const employeeOptions = employees.map((item) => ({ value: item.id, label: `${item.employeeNo} / ${item.name}` }));
  function createAttendance() { setDialog({ title: "登记考勤", fields: [{ name: "employee_id", label: "员工", type: "select", required: true, options: employeeOptions }, { name: "attendance_date", label: "考勤日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "attendance_type", label: "考勤类型", required: true, defaultValue: "出勤" }, { name: "remark", label: "备注", type: "textarea" }], submit: (v) => void action("/hr/attendance-records", { employee_id: v.employee_id, attendance_date: v.attendance_date, attendance_type: v.attendance_type, remark: v.remark || undefined }, "考勤已登记") }); }
  function createPerformance() { setDialog({ title: "登记绩效", fields: [{ name: "employee_id", label: "员工", type: "select", required: true, options: employeeOptions }, { name: "period_start", label: "周期开始", type: "date", required: true }, { name: "period_end", label: "周期结束", type: "date", required: true }, { name: "score", label: "评分", type: "number", defaultValue: "100" }, { name: "grade", label: "等级", defaultValue: "A" }], submit: (v) => void action("/hr/performance-records", { employee_id: v.employee_id, period_start: v.period_start, period_end: v.period_end, score: v.score, grade: v.grade }, "绩效已登记") }); }
  function generateLedger() { setDialog({ title: "生成薪资台账", fields: [{ name: "employee_id", label: "员工", type: "select", required: true, options: employeeOptions }, { name: "period_start", label: "周期开始", type: "date", required: true }, { name: "period_end", label: "周期结束", type: "date", required: true }, { name: "base_salary", label: "基本工资", type: "number", required: true, defaultValue: "0" }], submit: (v) => void action("/hr/payroll-ledgers/generate", { employee_id: v.employee_id, period_start: v.period_start, period_end: v.period_end, currency: "CNY", base_salary: v.base_salary }, "薪资台账已生成") }); }
  function createPayment() { setDialog({ title: "登记工资支付", fields: [{ name: "amount", label: "支付金额", type: "number", required: true }, { name: "payment_date", label: "支付日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "payment_method", label: "支付方式", required: true, defaultValue: "银行转账" }], submit: (v) => void action("/hr/salary-payments", { payment_date: v.payment_date, amount: v.amount, currency: "CNY", payment_method: v.payment_method }, "工资支付草稿已创建") }); }
  const employeeName = (id: string) => employees.find((item) => item.id === id)?.name ?? id;
  const employeeColumns: ColumnDef<Employee>[] = [{ accessorKey: "employeeNo", header: "工号" }, { accessorKey: "name", header: "姓名" }, { id: "org", header: "部门/岗位", cell: ({ row }) => `${row.original.department?.name ?? "-"} / ${row.original.position?.name ?? "-"}` }, { accessorKey: "employeeType", header: "类型" }, { accessorKey: "employmentStatus", header: "状态" }];
  const recordColumns: ColumnDef<RecordItem>[] = [{ id: "type", header: "类型", cell: ({ row }) => row.original.attendanceDate ? "考勤" : "绩效" }, { id: "employee", header: "员工", cell: ({ row }) => employeeName(row.original.employeeId) }, { id: "period", header: "日期/周期", cell: ({ row }) => row.original.attendanceDate?.slice(0, 10) ?? `${row.original.periodStart?.slice(0, 10)} 至 ${row.original.periodEnd?.slice(0, 10)}` }, { id: "result", header: "结果", cell: ({ row }) => row.original.attendanceType ?? `${row.original.grade ?? "-"} ${row.original.score ?? ""}` }];
  const ledgerColumns: ColumnDef<Ledger>[] = [{ id: "employee", header: "员工", cell: ({ row }) => employeeName(row.original.employeeId) }, { id: "period", header: "周期", cell: ({ row }) => `${row.original.periodStart.slice(0, 10)} 至 ${row.original.periodEnd.slice(0, 10)}` }, { id: "amount", header: "应付", cell: ({ row }) => `${row.original.payableAmount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => <>{row.original.status === "draft" && <Button size="sm" variant="secondary" onClick={() => void action(`/hr/payroll-ledgers/${row.original.id}/confirm`, undefined, "薪资台账已确认")}>确认</Button>}{row.original.status === "confirmed" && <Button size="sm" variant="secondary" onClick={() => void action(`/hr/payroll-ledgers/${row.original.id}/close`, undefined, "薪资台账已关闭")}>关闭</Button>}</> }];
  const paymentColumns: ColumnDef<Payment>[] = [{ accessorKey: "paymentNo", header: "支付单号" }, { id: "date", header: "日期", cell: ({ row }) => row.original.paymentDate.slice(0, 10) }, { id: "amount", header: "金额", cell: ({ row }) => `${row.original.amount} ${row.original.currency}` }, { accessorKey: "status", header: "状态" }];
  if (loading) return <><PageHeader title="人事" /><LoadingState /></>;
  return <><PageHeader title="人事"><div className="page-actions"><Button onClick={createAttendance}>登记考勤</Button><Button variant="secondary" onClick={createPerformance}>登记绩效</Button><Button variant="secondary" onClick={generateLedger}>生成薪资台账</Button><Button variant="secondary" onClick={createPayment}>登记工资支付</Button></div></PageHeader><ActionDialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onSubmit={(values) => { dialog?.submit(values); setDialog(null); }} />{message && <section className="panel panel-body status-success" role="status">{message}</section>}{error && <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>}<section className="panel"><div className="panel-heading"><h2>员工目录</h2></div><div className="panel-body"><DataTable columns={employeeColumns} data={employees} empty={<EmptyState title="暂无员工" />} /></div></section><section className="panel"><div className="panel-heading"><h2>考勤与绩效</h2></div><div className="panel-body"><DataTable columns={recordColumns} data={[...attendance, ...performance]} empty={<EmptyState title="暂无考勤或绩效记录" />} /></div></section><section className="panel"><div className="panel-heading"><h2>薪资台账</h2></div><div className="panel-body"><DataTable columns={ledgerColumns} data={ledgers} empty={<EmptyState title="暂无薪资台账" />} /></div></section><section className="panel"><div className="panel-heading"><h2>工资支付</h2></div><div className="panel-body"><DataTable columns={paymentColumns} data={payments} empty={<EmptyState title="暂无工资支付" />} /></div></section></>;
}
