"use client";

import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog, type ActionField } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "../../components/ui/sheet";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";
import { DailyReportsPanel } from "../../components/production/daily-reports-panel";
import { OutsourceLogisticsPanel } from "../../components/production/outsource-logistics-panel";

type Unit = { id: string; name: string; isActive: boolean };
type Location = { id: string; name: string; locationType: "workshop" | "outsource_site"; isActive: boolean };
type Operation = { id: string; operationName: string; defaultUnitId?: string | null; isActive: boolean };
type Order = { orderNo: string; quantity: string; status: string; boms: Array<{ id: string; version: number; status: string }> };
type ProductionOrder = { id: string; productionOrderNo: string; orderNo: string; executionMode: "in_house" | "outsourced"; status: string; plannedQuantity: string; executionLocation: Location; operations: Array<{ id: string; operationNameSnapshot: string; targetQuantity: string; status: string }> };

export default function ProductionPage() {
  const [orders, setOrders] = useState<Order[]>([]); const [locations, setLocations] = useState<Location[]>([]); const [operations, setOperations] = useState<Operation[]>([]); const [units, setUnits] = useState<Unit[]>([]); const [records, setRecords] = useState<ProductionOrder[]>([]); const [query, setQuery] = useState(""); const [selected, setSelected] = useState<ProductionOrder | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [dialog, setDialog] = useState<{ title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void } | null>(null);
  async function load() { setLoading(true); setError(""); try { const [sales, sites, process, production, unitData] = await Promise.all([apiGet<Order[]>("/sales-orders"), apiGet<Location[]>("/production/locations"), apiGet<Operation[]>("/production/operations"), apiGet<ProductionOrder[]>("/production/orders"), apiGet<Unit[]>("/units")]); setOrders(sales.data.filter((item) => item.status === "confirmed" && item.boms.some((bom) => bom.status === "published"))); setLocations(sites.data); setOperations(process.data); setRecords(production.data); setUnits(unitData.data.filter((unit) => unit.isActive)); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "生产数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function run(path: string, body: unknown, success: string) { setError(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "操作失败"); } }
  const visible = useMemo(() => records.filter((item) => !query || `${item.productionOrderNo} ${item.orderNo} ${item.status}`.toLowerCase().includes(query.toLowerCase())), [records, query]);
  const activeLocations = locations.filter((item) => item.isActive); const defaultUnit = operations.find((item) => item.isActive && item.defaultUnitId)?.defaultUnitId;
  function openLocation() { setDialog({ title: "新建生产地点", fields: [{ name: "name", label: "地点名称", required: true }, { name: "location_type", label: "地点类型", required: true, defaultValue: "workshop" }], submit: (v) => void run("/production/locations", v, "生产地点已创建") }); }
  function openOperation() { setDialog({ title: "新建工序", fields: [{ name: "operation_name", label: "工序名称", required: true }, { name: "default_unit_id", label: "默认单位 ID", required: true }], submit: (v) => void run("/production/operations", v, "工序已创建") }); }
  function openProductionOrder() { setDialog({ title: "新建生产单", fields: [{ name: "order_no", label: "订单号", required: true }, { name: "execution_mode", label: "执行方式", required: true, defaultValue: "in_house" }, { name: "execution_location_id", label: "执行地点 ID", required: true }], submit: (v) => { const source = orders.find((item) => item.orderNo === v.order_no); const bom = source?.boms.find((item) => item.status === "published"); if (!source || !bom || !defaultUnit) { setError("请选择已确认且有已发布 BOM 的订单，并维护带默认单位的工序"); return; } void run("/production/orders", { order_no: source.orderNo, bom_id: bom.id, bom_version: bom.version, execution_mode: v.execution_mode, execution_location_id: v.execution_location_id, planned_quantity: source.quantity, unit_id: defaultUnit }, "生产单草稿已创建"); } }); }
  function addOperation(order: ProductionOrder) { const operation = operations.find((item) => item.isActive); if (!operation) { setError("请先维护启用工序"); return; } void run(`/production/orders/${order.id}/operations`, { operation_id: operation.id, sequence_no: order.operations.length + 1, target_quantity: order.plannedQuantity }, "工序任务已添加"); }
  function start(order: ProductionOrder) { void run(`/production/orders/${order.id}/transition`, { target: "in_progress", reason: "开始生产" }, "生产单已启动"); }
  return <><PageHeader title="生产" description="生产单、工序、日报和 QC"><Button onClick={openProductionOrder}>新建生产单</Button></PageHeader><ActionDialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onSubmit={(v) => { dialog?.submit(v); setDialog(null); }} />{message && <section className="panel panel-body status-success">{message}</section>}{error ? <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section> : loading ? <LoadingState /> : <><section className="panel"><div className="panel-heading"><h2>基础资料</h2><div className="page-actions"><Button variant="secondary" onClick={openLocation}>新建地点</Button><Button variant="secondary" onClick={openOperation}>新建工序</Button></div></div><div className="panel-body"><span className="module-stat"><strong>{activeLocations.length}</strong> 个启用地点</span><span className="module-stat"><strong>{operations.filter((item) => item.isActive).length}</strong> 个启用工序</span><span className="module-stat"><strong>{units.length}</strong> 个可用单位</span></div></section><section className="panel"><div className="panel-heading"><h2>生产单</h2></div><div className="panel-body"><div className="filter-bar"><label>搜索生产单、订单号或状态<Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="输入关键词" /></label></div><div className="table-wrap"><table className="data-table"><thead><tr><th>生产单号</th><th>订单号</th><th>执行方式</th><th>地点</th><th>计划数</th><th>工序</th><th>状态</th><th>操作</th></tr></thead><tbody>{visible.map((order) => <tr key={order.id}><td><Button variant="link" onClick={() => setSelected(order)}>{order.productionOrderNo}</Button></td><td>{order.orderNo}</td><td>{order.executionMode === "in_house" ? "厂内" : "外加工"}</td><td>{order.executionLocation.name}</td><td>{order.plannedQuantity}</td><td>{order.operations.map((operation) => operation.operationNameSnapshot).join("、") || "未配置"}</td><td>{order.status}</td><td>{order.status === "draft" && <><Button variant="secondary" onClick={() => addOperation(order)}>添加工序</Button><Button variant="secondary" onClick={() => start(order)}>启动</Button></>}</td></tr>)}</tbody></table>{!visible.length && <EmptyState title="暂无生产单" description="调整筛选条件或新建生产单" />}</div></div></section></>}{<Sheet open={Boolean(selected)} onOpenChange={(open) => { if (!open) setSelected(null); }}><SheetContent><SheetHeader><SheetTitle>{selected?.productionOrderNo}</SheetTitle><SheetDescription>生产单详情</SheetDescription></SheetHeader>{selected && <div className="detail-list"><p>订单号：{selected.orderNo}</p><p>执行方式：{selected.executionMode === "in_house" ? "厂内" : "外加工"}</p><p>地点：{selected.executionLocation.name}</p><p>计划数量：{selected.plannedQuantity}</p><p>工序：{selected.operations.map((item) => `${item.operationNameSnapshot}（${item.targetQuantity}）`).join("、") || "未配置"}</p></div>}</SheetContent></Sheet>}<div className="production-subflows"><OutsourceLogisticsPanel /><DailyReportsPanel /></div></>;
}
