"use client";

import { useEffect, useState } from "react";
import { PageHeader } from "../../components/layout/app-shell";
import { Button } from "../../components/ui/button";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";

type Location = { id: string; name: string; locationType: string; isActive: boolean };
type Operation = { id: string; operationName: string; defaultUnitId?: string; isActive: boolean };
type Order = { orderNo: string; quantity: string; status: string; boms: Array<{ id: string; version: number; status: string }> };
type ProductionOrder = { id: string; productionOrderNo: string; orderNo: string; executionMode: string; status: string; plannedQuantity: string; executionLocation: Location; operations: Array<{ id: string; operationNameSnapshot: string; targetQuantity: string; status: string }> };

export default function ProductionPage() {
  const [orders, setOrders] = useState<Order[]>([]), [locations, setLocations] = useState<Location[]>([]), [operations, setOperations] = useState<Operation[]>([]), [records, setRecords] = useState<ProductionOrder[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(""), [message, setMessage] = useState("");
  async function load() { setLoading(true); setError(""); try { const [sales, sites, process, production] = await Promise.all([apiGet<Order[]>("/sales-orders"), apiGet<Location[]>("/production/locations"), apiGet<Operation[]>("/production/operations"), apiGet<ProductionOrder[]>("/production/orders")]); setOrders(sales.data.filter((item) => item.status === "confirmed")); setLocations(sites.data); setOperations(process.data); setRecords(production.data); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "生产数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function action(path: string, body?: unknown, success = "操作已完成") { setError(""); try { await apiPost(path, body); setMessage(success); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "操作失败"); } }
  function create() { const order = orders.find((item) => item.boms.some((bom) => bom.status === "published")); const location = locations.find((item) => item.isActive && item.locationType === "workshop"); const unitId = operations.find((item) => item.defaultUnitId)?.defaultUnitId; if (!order || !location || !unitId) { setError("请先准备已确认且有已发布 BOM 的销售单、启用的厂内车间和带默认单位的工序"); return; } const bom = order.boms.find((item) => item.status === "published")!; void action("/production/orders", { order_no: order.orderNo, bom_id: bom.id, bom_version: bom.version, execution_mode: "in_house", execution_location_id: location.id, planned_quantity: order.quantity, unit_id: unitId }, "生产单草稿已创建"); }
  function addOperation(order: ProductionOrder) { const operation = operations.find((item) => item.isActive); if (!operation) { setError("请先维护启用的工序"); return; } void action(`/production/orders/${order.id}/operations`, { operation_id: operation.id, sequence_no: order.operations.length + 1, target_quantity: order.plannedQuantity }, "工序任务已添加"); }
  return <><PageHeader title="生产" description="生产基础资料、订单生产单、工序任务与状态推进"><Button onClick={create}>新建厂内生产单</Button></PageHeader>{message && <section className="panel panel-body status-success">{message}</section>}{error ? <section className="panel"><ErrorState message={error} onRetry={() => { void load(); }} /></section> : loading ? <LoadingState /> : <div className="workbench-grid"><section className="panel"><div className="panel-heading"><h2>生产基础资料</h2></div><div className="panel-body">启用地点 {locations.filter((item) => item.isActive).length} 个，启用工序 {operations.filter((item) => item.isActive).length} 个。日报、领料和成品链路尚未开放。</div></section><section className="panel"><div className="panel-heading"><h2>生产单</h2></div><div className="table-wrap"><table className="data-table"><thead><tr><th>生产单号</th><th>订单号</th><th>执行方式</th><th>地点</th><th>计划数</th><th>状态</th><th>操作</th></tr></thead><tbody>{records.map((order) => <tr key={order.id}><td>{order.productionOrderNo}</td><td>{order.orderNo}</td><td>{order.executionMode === "in_house" ? "厂内" : "外加工"}</td><td>{order.executionLocation.name}</td><td>{order.plannedQuantity}</td><td>{order.status}</td><td>{order.executionMode === "in_house" && order.status === "draft" && <Button variant="secondary" onClick={() => addOperation(order)}>添加工序</Button>}{order.status === "draft" && <Button variant="secondary" onClick={() => void action(`/production/orders/${order.id}/transition`, { target: "in_progress", reason: "开始生产" }, "生产单已启动")}>启动</Button>}</td></tr>)}</tbody></table>{!records.length && <EmptyState title="暂无生产单" description="从已确认且已发布 BOM 的订单创建生产单" />}</div></section></div>}</>;
}
