"use client";

import { useEffect, useMemo, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { PageHeader } from "../layout/app-shell";
import { ActionDialog, type ActionField } from "../ui/action-dialog";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "../ui/select";
import { DataTable } from "../data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../feedback/states";
import { ApiClientError, apiGet, apiPatch, apiPost, apiRequest } from "../../lib/api-client";

type Department = { id: string; code: string; name: string; remark?: string | null; isActive: boolean; deletedAt?: string | null; updatedAt: string; _count?: { positions: number; employees: number } };
type Position = { id: string; code: string; name: string; departmentId: string; department?: { code: string; name: string }; remark?: string | null; isActive: boolean; deletedAt?: string | null; updatedAt: string; _count?: { employees: number } };
type DialogState = { title: string; fields: ActionField[]; submit: (values: Record<string, string>) => Promise<void> };
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export function OrganizationPool({ kind }: { kind: "departments" | "positions" }) {
  const isDepartment = kind === "departments";
  const label = isDepartment ? "部门" : "岗位";
  const [departments, setDepartments] = useState<Department[]>([]);
  const [records, setRecords] = useState<Array<Department | Position>>([]);
  const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [departmentId, setDepartmentId] = useState("all"); const [dialog, setDialog] = useState<DialogState | null>(null);
  async function load() { setLoading(true); setError(""); try { const [items, departmentRows] = await Promise.all([apiGet<Array<Department | Position>>(`/production/${kind}?include_deleted=true`), isDepartment ? Promise.resolve({ data: [] as Department[] }) : apiGet<Department[]>("/production/departments")]); setRecords(items.data); setDepartments(departmentRows.data); } catch (cause) { setError(messageOf(cause, `${label}池加载失败`)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [kind]);
  async function request(path: string, options: RequestInit, success: string) { setError(""); try { await apiRequest(path, options); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  function fields(item?: Department | Position): ActionField[] { const base: ActionField[] = [{ name: "code", label: `${label}编码`, required: true, defaultValue: item?.code }, { name: "name", label: `${label}名称`, required: true, defaultValue: item?.name }, { name: "remark", label: "备注", type: "textarea", defaultValue: item?.remark ?? "" }]; return isDepartment ? base : [{ name: "department_id", label: "所属部门", type: "select", required: true, defaultValue: item && "departmentId" in item ? item.departmentId : undefined, options: departments.filter((row) => row.isActive).map((row) => ({ value: row.id, label: `${row.code} / ${row.name}` })) }, ...base]; }
  function openCreate() { setDialog({ title: `新建${label}`, fields: fields(), submit: async (values) => { await request(`/production/${kind}`, { method: "POST", body: JSON.stringify({ ...values, remark: values.remark || undefined }) }, `${label}已创建`); } }); }
  function openEdit(item: Department | Position) { setDialog({ title: `编辑${label}`, fields: fields(item), submit: async (values) => { await request(`/production/${kind}/${item.id}`, { method: "PATCH", body: JSON.stringify({ ...values, remark: values.remark || undefined }) }, `${label}已更新`); } }); }
  const visible = useMemo(() => records.filter((item) => { const deleted = Boolean(item.deletedAt); const state = deleted ? "deleted" : item.isActive ? "active" : "inactive"; const matchQuery = `${item.code} ${item.name}`.toLowerCase().includes(query.toLowerCase()); return matchQuery && (status === "all" || status === state) && (isDepartment || departmentId === "all" || (item as Position).departmentId === departmentId); }), [records, query, status, departmentId, isDepartment]);
  const columns: ColumnDef<Department | Position>[] = [{ accessorKey: "code", header: `${label}编码` }, { accessorKey: "name", header: `${label}名称` }, ...(isDepartment ? [{ id: "positions", header: "岗位数", cell: ({ row }: any) => (row.original as Department)._count?.positions ?? 0 }, { id: "employees", header: "员工数", cell: ({ row }: any) => (row.original as Department)._count?.employees ?? 0 }] : [{ id: "department", header: "所属部门", cell: ({ row }: any) => { const item = row.original as Position; return item.department ? `${item.department.code} / ${item.department.name}` : "-"; } }, { id: "employees", header: "员工数", cell: ({ row }: any) => (row.original as Position)._count?.employees ?? 0 }]), { id: "status", header: "状态", cell: ({ row }) => row.original.deletedAt ? "已删除" : row.original.isActive ? "启用" : "停用" }, { accessorKey: "remark", header: "备注" }, { id: "actions", header: "操作", cell: ({ row }) => { const item = row.original; return <div className="action-row">{item.deletedAt ? <Button size="sm" variant="secondary" onClick={() => void request(`/production/${kind}/${item.id}/restore`, { method: "POST" }, `${label}已恢复`)}>恢复</Button> : <><Button size="sm" variant="secondary" onClick={() => openEdit(item)}>编辑</Button><Button size="sm" variant="ghost" onClick={() => void request(`/production/${kind}/${item.id}/active`, { method: "PATCH", body: JSON.stringify({ is_active: !item.isActive }) }, `${label}已${item.isActive ? "停用" : "启用"}`)}>{item.isActive ? "停用" : "启用"}</Button><Button size="sm" variant="destructive" onClick={() => void request(`/production/${kind}/${item.id}`, { method: "DELETE" }, `${label}已删除`)}>删除</Button></>}</div>; } }];
  if (loading) return <><PageHeader title={`${label}池`} /><LoadingState /></>;
  return <><PageHeader title={`${label}池`} description={`统一维护${label}主数据`}><Button onClick={openCreate}>新建{label}</Button></PageHeader><ActionDialog open={Boolean(dialog)} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onOpenChange={(open) => { if (!open) setDialog(null); }} onSubmit={(values) => { void dialog?.submit(values); setDialog(null); }} />{message && <section className="panel panel-body status-success">{message}</section>}{error && <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>}<section className="panel"><div className="panel-body"><div className="filter-bar"><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`搜索${label}编码或名称`} /><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部状态</SelectItem><SelectItem value="active">启用</SelectItem><SelectItem value="inactive">停用</SelectItem><SelectItem value="deleted">已删除</SelectItem></SelectContent></Select>{!isDepartment && <Select value={departmentId} onValueChange={setDepartmentId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">全部部门</SelectItem>{departments.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select>}</div><DataTable columns={columns} data={visible} empty={<EmptyState title={`暂无${label}`} action={<Button onClick={openCreate}>新建{label}</Button>} />} /></div></section></>;
}
