"use client";

import { useEffect, useState } from "react";
import type { ColumnDef } from "@tanstack/react-table";
import { apiGet, apiPost, ApiClientError } from "../../lib/api-client";
import { ActionDialog, type ActionField } from "../ui/action-dialog";
import { Button } from "../ui/button";
import { DataTable } from "../data/data-table";
import { EmptyState } from "../feedback/states";

type Source = { source_id: string; source_type: string; order_no: string; production_order_no: string; production_order_id: string; unit: string; available_quantity: string; source_status: string };
type Submission = { id: string; submissionNo: string; orderNo: string; sourceType: string; submittedQuantity: string; status: string; unitNameSnapshot: string; qcRecords: Array<{ id: string; conclusion: string; inspectedQuantity: string }> };
type DialogState = { title: string; fields: ActionField[]; submit: (values: Record<string, string>) => void };
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export function FinishedGoodsQcPanel() {
  const [sources, setSources] = useState<Source[]>([]); const [submissions, setSubmissions] = useState<Submission[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [dialog, setDialog] = useState<DialogState | null>(null);
  async function load() { setError(""); try { const [sourceResult, submissionResult] = await Promise.all([apiGet<Source[]>("/finished-goods/qc/sources"), apiGet<Submission[]>("/finished-goods/inspection-submissions")]); setSources(sourceResult.data); setSubmissions(submissionResult.data); } catch (cause) { setError(messageOf(cause, "成品质检数据加载失败")); } }
  useEffect(() => { void load(); }, []);
  async function run(action: () => Promise<unknown>, success: string) { setError(""); try { await action(); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  function createSubmission(source: Source) { void run(() => apiPost("/finished-goods/inspection-submissions", { production_order_id: source.production_order_id, source_type: source.source_type, source_id: source.source_id, submitted_quantity: source.available_quantity, submission_date: new Date().toISOString().slice(0, 10) }), "成品送检单已创建"); }
  function submit(id: string) { void run(() => apiPost(`/finished-goods/inspection-submissions/${id}/submit`), "送检单已提交"); }
  function openQc() { setDialog({ title: "录入成品质检", fields: [{ name: "submission_id", label: "送检单", type: "select", required: true, options: submissions.filter((item) => ["submitted", "inspecting"].includes(item.status)).map((item) => ({ value: item.id, label: `${item.submissionNo} / ${item.orderNo} / ${item.submittedQuantity} ${item.unitNameSnapshot}` })) }, { name: "inspection_date", label: "检验日期", type: "date", required: true, defaultValue: new Date().toISOString().slice(0, 10) }, { name: "inspected_quantity", label: "本次检验数量", type: "number", required: true }, { name: "qualified_quantity", label: "合格数量", type: "number", required: true, defaultValue: "0" }, { name: "conditional_accept_quantity", label: "条件接收数量", type: "number", required: true, defaultValue: "0" }, { name: "rejected_quantity", label: "不合格数量", type: "number", required: true, defaultValue: "0" }, { name: "rejection_reason", label: "不合格原因", type: "textarea" }], submit: (v) => void run(() => apiPost("/finished-goods/qc-records", v), "成品质检已保存") }); }
  const sourceColumns: ColumnDef<Source>[] = [{ accessorKey: "order_no", header: "订单号" }, { accessorKey: "production_order_no", header: "生产单" }, { id: "source", header: "来源", cell: ({ row }) => row.original.source_type === "in_house_completion" ? "厂内完工" : "外加工回厂" }, { accessorKey: "available_quantity", header: "数量" }, { accessorKey: "unit", header: "单位" }, { accessorKey: "source_status", header: "状态" }, { id: "actions", header: "操作", cell: ({ row }) => <Button size="sm" onClick={() => createSubmission(row.original)}>创建送检</Button> }];
  const submissionColumns: ColumnDef<Submission>[] = [{ accessorKey: "submissionNo", header: "送检单" }, { accessorKey: "orderNo", header: "订单号" }, { id: "quantity", header: "数量", cell: ({ row }) => `${row.original.submittedQuantity} ${row.original.unitNameSnapshot}` }, { accessorKey: "status", header: "状态" }, { id: "qc", header: "质检", cell: ({ row }) => row.original.qcRecords.map((item) => `${item.conclusion}:${item.inspectedQuantity}`).join("、") || "-" }, { id: "actions", header: "操作", cell: ({ row }) => row.original.status === "draft" ? <Button size="sm" variant="secondary" onClick={() => submit(row.original.id)}>提交送检</Button> : null }];
  return <section className="panel" style={{ gridColumn: "1 / -1" }}><ActionDialog open={Boolean(dialog)} onOpenChange={(open) => { if (!open) setDialog(null); }} title={dialog?.title ?? "操作"} fields={dialog?.fields ?? []} onAddCategory={(field) => setError(`${field.label}为业务记录，请在对应模块建立`)} onSubmit={(values) => { dialog?.submit(values); setDialog(null); }} /><div className="panel-heading"><h2>成品送检与质检</h2><div className="page-actions"><Button variant="secondary" onClick={openQc}>录入质检</Button><Button variant="ghost" onClick={() => void load()}>刷新</Button></div></div>{message && <p className="status-success panel-body" role="status">{message}</p>}{error && <p className="status-error panel-body" role="alert">{error}</p>}<div className="panel-body"><h3>待送检来源</h3><DataTable columns={sourceColumns} data={sources} empty={<EmptyState title="暂无可送检来源" />} /><h3>送检记录</h3><DataTable columns={submissionColumns} data={submissions} empty={<EmptyState title="暂无送检记录" />} /></div></section>;
}
