"use client";

import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { apiGet, apiPost, ApiClientError } from "../../lib/api-client";
import { Button } from "../ui/button";

type Source = { source_id: string; source_type: string; order_no: string; production_order_no: string; production_order_id: string; unit: string; available_quantity: string; source_status: string };
type Submission = { id: string; submissionNo: string; orderNo: string; sourceType: string; submittedQuantity: string; status: string; unitNameSnapshot: string; qcRecords: Array<{ id: string; conclusion: string; inspectedQuantity: string }> };
type QcForm = { submission_id: string; inspection_date: string; inspected_quantity: string; qualified_quantity: string; conditional_accept_quantity: string; rejected_quantity: string; rejection_reason?: string };

const today = () => new Date().toISOString().slice(0, 10);
const messageOf = (cause: unknown, fallback: string) => cause instanceof ApiClientError ? cause.message : fallback;

export function FinishedGoodsQcPanel() {
  const [sources, setSources] = useState<Source[]>([]); const [submissions, setSubmissions] = useState<Submission[]>([]); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const form = useForm<QcForm>({ defaultValues: { inspection_date: today(), conditional_accept_quantity: "0", rejected_quantity: "0" } });
  async function load() { setError(""); try { const [sourceResult, submissionResult] = await Promise.all([apiGet<Source[]>("/finished-goods/qc/sources"), apiGet<Submission[]>("/finished-goods/inspection-submissions")]); setSources(sourceResult.data); setSubmissions(submissionResult.data); } catch (cause) { setError(messageOf(cause, "成品 QC 数据加载失败")); } }
  useEffect(() => { void load(); }, []);
  async function run(action: () => Promise<unknown>, success: string) { setError(""); try { await action(); setMessage(success); await load(); } catch (cause) { setError(messageOf(cause, "操作失败")); } }
  function createSubmission(source: Source) { void run(() => apiPost("/finished-goods/inspection-submissions", { production_order_id: source.production_order_id, source_type: source.source_type, source_id: source.source_id, submitted_quantity: source.available_quantity, submission_date: today() }), "成品送检单已创建"); }
  function submit(id: string) { void run(() => apiPost(`/finished-goods/inspection-submissions/${id}/submit`), "送检单已提交"); }
  function createQc(values: QcForm) { void run(() => apiPost("/finished-goods/qc-records", values), "成品 QC 已保存"); }
  return <section className="panel" style={{ gridColumn: "1 / -1" }}><div className="panel-heading"><h2>成品送检与 QC</h2><span className="panel-note">合格/条件接收可供后续成品入库；当前不直接改变库存</span></div>{message && <p className="status-success panel-body" role="status">{message}</p>}{error && <p className="status-error panel-body" role="alert">{error}</p>}<div className="panel-body"><h3>待送检来源</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>订单号</th><th>生产单</th><th>来源</th><th>数量</th><th>单位</th><th>状态</th><th>操作</th></tr></thead><tbody>{sources.map((source) => <tr key={`${source.source_type}-${source.source_id}`}><td>{source.order_no}</td><td>{source.production_order_no}</td><td>{source.source_type === "in_house_completion" ? "厂内完工" : "外加工回厂"}</td><td>{source.available_quantity}</td><td>{source.unit}</td><td>{source.source_status}</td><td><Button type="button" onClick={() => createSubmission(source)}>创建送检</Button></td></tr>)}</tbody></table>{!sources.length && <p className="panel-note">暂无可送检来源。</p>}</div><h3>QC 录入</h3><form className="form-grid" onSubmit={form.handleSubmit(createQc)}><label>送检单<select {...form.register("submission_id", { required: true })}><option value="">请选择已提交送检单</option>{submissions.filter((item) => ["submitted", "inspecting"].includes(item.status)).map((item) => <option key={item.id} value={item.id}>{item.submissionNo} / {item.orderNo} / {item.submittedQuantity} {item.unitNameSnapshot}</option>)}</select></label><label>检验日期<input type="date" {...form.register("inspection_date", { required: true })} /></label><label>本次检验数量<input type="number" min="0.0001" step="0.0001" {...form.register("inspected_quantity", { required: true })} /></label><label>合格数量<input type="number" min="0" step="0.0001" {...form.register("qualified_quantity", { required: true })} /></label><label>条件接收数量<input type="number" min="0" step="0.0001" {...form.register("conditional_accept_quantity", { required: true })} /></label><label>不合格数量<input type="number" min="0" step="0.0001" {...form.register("rejected_quantity", { required: true })} /></label><label>不合格原因<textarea {...form.register("rejection_reason")} /></label><Button type="submit">保存 QC 记录</Button></form><h3>送检记录</h3><div className="table-wrap"><table className="data-table"><thead><tr><th>送检单</th><th>订单号</th><th>数量</th><th>状态</th><th>QC</th><th>操作</th></tr></thead><tbody>{submissions.map((item) => <tr key={item.id}><td>{item.submissionNo}</td><td>{item.orderNo}</td><td>{item.submittedQuantity} {item.unitNameSnapshot}</td><td>{item.status}</td><td>{item.qcRecords.map((qc) => `${qc.conclusion}:${qc.inspectedQuantity}`).join("、") || "-"}</td><td>{item.status === "draft" && <Button type="button" variant="secondary" onClick={() => submit(item.id)}>提交送检</Button>}</td></tr>)}</tbody></table>{!submissions.length && <p className="panel-note">暂无送检记录。</p>}</div></div></section>;
}
