"use client";

import { useEffect, useState } from "react";
import { Download, RefreshCw } from "lucide-react";
import { PageHeader } from "../../components/layout/app-shell";
import { ActionDialog } from "../../components/ui/action-dialog";
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { DataTable } from "../../components/data/data-table";
import { EmptyState, ErrorState, LoadingState } from "../../components/feedback/states";
import { ApiClientError, apiGet, apiPost } from "../../lib/api-client";
import { displayField, displayStatus, displayText } from "../../lib/display-text";

type ReportRow = Record<string, unknown>;
type Alert = { source_id: string; source_type: string; alert_type: string; order_no: string | null; severity: string; title: string; suggestion: string; status: string };
const reports = [{ key: "orders", label: "订单推进" }, { key: "procurement-payables", label: "采购与应付" }, { key: "inventory", label: "库存" }, { key: "production-qc", label: "生产与质检" }, { key: "payroll", label: "薪资" }];

export default function ReportsPage() {
  const [tab, setTab] = useState("orders"); const [rows, setRows] = useState<ReportRow[]>([]); const [alerts, setAlerts] = useState<Alert[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [orderNo, setOrderNo] = useState(""); const [pendingAlert, setPendingAlert] = useState<{ item: Alert; status: "acknowledged" | "resolved" } | null>(null);
  async function load() { setLoading(true); setError(""); try { const query = orderNo ? `?${new URLSearchParams({ order_no: orderNo })}` : ""; if (tab === "alerts") setAlerts((await apiGet<Alert[]>(`/alerts${query}`)).data); else setRows((await apiGet<ReportRow[]>(`/reports/${tab}${query}`)).data); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "数据加载失败"); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [tab]);
  async function exportCsv() { const query = orderNo ? `?${new URLSearchParams({ order_no: orderNo })}` : ""; const response = await fetch(`/api/v1/reports/${tab}/export${query}`, { credentials: "include" }); if (!response.ok) { setError("导出失败，请缩小筛选范围后重试"); return; } const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = `${tab}.csv`; link.click(); URL.revokeObjectURL(url); }
  async function handleAlert(values: Record<string, string>) { if (!pendingAlert) return; try { await apiPost(`/alerts/${pendingAlert.item.source_id}/handle`, { status: pendingAlert.status, remark: values.remark }); setPendingAlert(null); await load(); } catch (cause) { setError(cause instanceof ApiClientError ? cause.message : "告警处理失败"); } }
  const alertColumns = [{ accessorKey: "severity", header: "级别", cell: ({ row }: { row: { original: Alert } }) => displayStatus(row.original.severity) }, { accessorKey: "title", header: "标题" }, { accessorKey: "order_no", header: "订单号", cell: ({ row }: { row: { original: Alert } }) => row.original.order_no ?? "-" }, { accessorKey: "status", header: "状态", cell: ({ row }: { row: { original: Alert } }) => displayStatus(row.original.status) }, { accessorKey: "suggestion", header: "建议" }, { id: "actions", header: "操作", cell: ({ row }: { row: { original: Alert } }) => row.original.status === "pending" ? <Button size="sm" variant="secondary" onClick={() => setPendingAlert({ item: row.original, status: "acknowledged" })}>确认</Button> : row.original.status === "acknowledged" ? <Button size="sm" variant="secondary" onClick={() => setPendingAlert({ item: row.original, status: "resolved" })}>解决</Button> : null }];
  const reportColumns = rows[0] ? Object.keys(rows[0]).map((key) => ({ accessorKey: key, header: displayField(key), cell: ({ row }: { row: { original: ReportRow } }) => { const value = row.original[key]; return typeof value === "object" ? JSON.stringify(value) : String(displayText(value ?? "-")); } })) : [];
  return <><PageHeader title="报表与告警"><div className="page-actions"><Button variant="secondary" onClick={() => void load()} title="刷新"><RefreshCw size={15} /> 刷新</Button></div></PageHeader><ActionDialog open={Boolean(pendingAlert)} onOpenChange={(open) => { if (!open) setPendingAlert(null); }} title="处理告警" fields={[{ name: "remark", label: "处理备注", type: "textarea", required: true }]} onSubmit={(values) => void handleAlert(values)} /><section className="panel"><div className="panel-body filter-bar"><label>订单号 <Input value={orderNo} onChange={(event) => setOrderNo(event.target.value)} placeholder="可选" /></label><Button variant="secondary" onClick={() => void load()}>筛选</Button></div></section><div className="tabs">{reports.map((item) => <Button key={item.key} variant={tab === item.key ? "default" : "secondary"} onClick={() => setTab(item.key)}>{item.label}</Button>)}<Button variant={tab === "alerts" ? "default" : "secondary"} onClick={() => setTab("alerts")}>告警中心</Button></div>{error && <section className="panel"><ErrorState message={error} onRetry={() => void load()} /></section>}{loading ? <LoadingState /> : tab === "alerts" ? <section className="panel"><div className="panel-body"><DataTable columns={alertColumns} data={alerts} empty={<EmptyState title="暂无待处理告警" />} /></div></section> : <section className="panel"><div className="panel-heading"><h2>{reports.find((item) => item.key === tab)?.label}</h2><Button variant="secondary" onClick={() => void exportCsv()}><Download size={15} /> 导出表格</Button></div><div className="panel-body"><DataTable columns={reportColumns} data={rows} empty={<EmptyState title="暂无报表数据" />} /></div></section>}</>;
}
