import { Controller, Get, Param, Query, Res, UseGuards } from "@nestjs/common";
import { IsDateString, IsInt, IsOptional, IsString, Max, Min } from "class-validator";
import { Type } from "class-transformer";
import type { Response } from "express";
import { AuthenticationGuard } from "../../platform/authorization/authentication.guard";
import { ModulePermissionGuard } from "../../platform/authorization/module-permission.guard";
import { RequireAnyModules } from "../../platform/authorization/require-any-modules.decorator";
import { ReportsService } from "./reports.service";
class ReportQueryDto { @IsOptional() @IsString() order_no?: string; @IsOptional() @IsDateString() from?: string; @IsOptional() @IsDateString() to?: string; @IsOptional() @IsString() status?: string; @IsOptional() @IsString() employee_id?: string; @IsOptional() @IsString() supplier_id?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) page = 1; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(200) page_size = 20; }
@Controller("reports") @UseGuards(AuthenticationGuard, ModulePermissionGuard) @RequireAnyModules("sales", "procurement", "production", "warehouse", "finance", "hr")
export class ReportsController { constructor(private readonly reports: ReportsService) {} @Get("orders") async orders(@Query() q: ReportQueryDto) { const r = await this.reports.orders(q); return { data: r.data, meta: { page: q.page, page_size: q.page_size, total: r.total } }; } @Get("procurement-payables") async procurement(@Query() q: ReportQueryDto) { const r = await this.reports.procurement(q); return { data: r.data, meta: { page: q.page, page_size: q.page_size, total: r.total } }; } @Get("inventory") async inventory(@Query() q: ReportQueryDto) { const r = await this.reports.inventory(q); return { data: r.data, meta: { page: q.page, page_size: q.page_size, total: r.total } }; } @Get("production-qc") async productionQc(@Query() q: ReportQueryDto) { const r = await this.reports.productionQc(q); return { data: r.data, meta: { page: q.page, page_size: q.page_size, total: r.total } }; } @Get("payroll") async payroll(@Query() q: ReportQueryDto) { const r = await this.reports.payroll(q); return { data: r.data, meta: { page: q.page, page_size: q.page_size, total: r.total } }; } @Get(":report/export") async export(@Param("report") report: string, @Query() q: ReportQueryDto, @Res() response: Response) { const body = await this.reports.export(report, q); response.setHeader("Content-Type", "text/csv; charset=utf-8"); response.setHeader("Content-Disposition", `attachment; filename="${report}.csv"`); return response.send(body); } }
