import { Injectable, UnprocessableEntityException } from "@nestjs/common";
import { Prisma } from "@prisma/client";
import { PrismaService } from "../../platform/database/prisma.service";

type Query = { order_no?: string; from?: string; to?: string; status?: string; employee_id?: string; supplier_id?: string; page?: number; page_size?: number };
type Row = Record<string, unknown>;

@Injectable()
export class ReportsService {
  constructor(private readonly prisma: PrismaService) {}
  async orders(query: Query) { const where = this.orderWhere(query); const [rows, total] = await Promise.all([this.prisma.salesOrder.findMany({ where, orderBy: { updatedAt: "desc" }, skip: this.skip(query), take: this.take(query), select: { orderNo: true, productName: true, quantity: true, unit: true, status: true, deliveryDate: true, updatedAt: true } }), this.prisma.salesOrder.count({ where })]); return { data: rows.map((row) => ({ order_no: row.orderNo, product_name: row.productName, quantity: row.quantity.toString(), unit: row.unit, status: row.status, delivery_date: row.deliveryDate, updated_at: row.updatedAt })), total }; }
  async procurement(query: Query) { const rows = await this.prisma.purchaseOrder.findMany({ where: { deletedAt: null, ...(query.order_no ? { orderNo: query.order_no } : {}), ...(query.supplier_id ? { supplierId: query.supplier_id } : {}), ...(query.status ? { status: query.status } : {}) }, orderBy: { updatedAt: "desc" }, skip: this.skip(query), take: this.take(query), select: { purchaseOrderNo: true, orderNo: true, supplierSnapshot: true, status: true, totalAmount: true, currency: true, updatedAt: true } }); return { data: rows.map((row) => ({ purchase_order_no: row.purchaseOrderNo, order_no: row.orderNo, supplier: row.supplierSnapshot, status: row.status, amount: row.totalAmount.toString(), currency: row.currency, updated_at: row.updatedAt })), total: rows.length }; }
  async inventory(query: Query) { const rows = await this.prisma.inventoryFact.findMany({ where: { ...(query.order_no ? { orderNo: query.order_no } : {}), ...(query.from || query.to ? { createdAt: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}) }, orderBy: { createdAt: "desc" }, skip: this.skip(query), take: this.take(query), select: { id: true, orderNo: true, inventoryCategory: true, quantityDelta: true, sourceType: true, sourceId: true, createdAt: true } }); return { data: rows.map((row) => ({ id: row.id, order_no: row.orderNo, inventory_category: row.inventoryCategory, quantity_delta: row.quantityDelta.toString(), source_type: row.sourceType, source_id: row.sourceId, created_at: row.createdAt })), total: rows.length }; }
  async productionQc(query: Query) { const rows = await this.prisma.finishedGoodsQcRecord.findMany({ where: { deletedAt: null, ...(query.order_no ? { orderNo: query.order_no } : {}), ...(query.status ? { status: query.status } : {}) }, orderBy: { updatedAt: "desc" }, skip: this.skip(query), take: this.take(query), select: { qcNo: true, orderNo: true, conclusion: true, status: true, inspectedQuantity: true, qualifiedQuantity: true, rejectedQuantity: true, inspectionDate: true } }); return { data: rows.map((row) => ({ qc_no: row.qcNo, order_no: row.orderNo, conclusion: row.conclusion, status: row.status, inspected_quantity: row.inspectedQuantity.toString(), qualified_quantity: row.qualifiedQuantity.toString(), rejected_quantity: row.rejectedQuantity.toString(), inspection_date: row.inspectionDate })), total: rows.length }; }
  async payroll(query: Query) { const rows = await this.prisma.payrollLedger.findMany({ where: { deletedAt: null, ...(query.employee_id ? { employeeId: query.employee_id } : {}), ...(query.status ? { status: query.status } : {}) }, orderBy: { periodStart: "desc" }, skip: this.skip(query), take: this.take(query), select: { ledgerNo: true, employeeId: true, periodStart: true, periodEnd: true, status: true, baseSalary: true, productionSourceAmount: true } }); return { data: rows.map((row) => ({ ledger_no: row.ledgerNo, employee_id: row.employeeId, period_start: row.periodStart, period_end: row.periodEnd, status: row.status, base_salary: row.baseSalary.toString(), production_source_amount: row.productionSourceAmount.toString() })), total: rows.length }; }
  async export(report: string, query: Query) { const result = await this.query(report, { ...query, page: 1, page_size: 5000 }); if (result.data.length >= 5000) throw new UnprocessableEntityException({ code: "EXPORT_LIMIT_EXCEEDED", message: "导出结果过多，请缩小筛选范围", details: [] }); return csv(result.data); }
  async query(report: string, query: Query): Promise<{ data: Row[]; total: number }> { switch (report) { case "orders": return this.orders(query) as Promise<{ data: Row[]; total: number }>; case "procurement-payables": return this.procurement(query) as Promise<{ data: Row[]; total: number }>; case "inventory": return this.inventory(query) as Promise<{ data: Row[]; total: number }>; case "production-qc": return this.productionQc(query) as Promise<{ data: Row[]; total: number }>; case "payroll": return this.payroll(query) as Promise<{ data: Row[]; total: number }>; default: throw new UnprocessableEntityException({ code: "REPORT_NOT_FOUND", message: "报表不存在", details: [] }); } }
  private orderWhere(query: Query): Prisma.SalesOrderWhereInput { return { deletedAt: null, ...(query.order_no ? { orderNo: query.order_no } : {}), ...(query.status ? { status: query.status } : {}), ...(query.from || query.to ? { updatedAt: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}) }; }
  private skip(query: Query) { return ((query.page ?? 1) - 1) * this.take(query); }
  private take(query: Query) { return Math.min(Math.max(query.page_size ?? 20, 1), 200); }
}

function csv(rows: Row[]) { if (!rows.length) return "\uFEFF"; const keys = [...new Set(rows.flatMap((row) => Object.keys(row)))]; const value = (item: unknown) => { const text = item === null || item === undefined ? "" : typeof item === "object" ? JSON.stringify(item) : String(item); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }; return `\uFEFF${[keys, ...rows.map((row) => keys.map((key) => value(row[key])))] .map((line) => line.join(",")).join("\r\n")}\r\n`; }
